/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account with email + password */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in with email + password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the refresh cookie into a fresh session
         * @description Requires the httpOnly refresh cookie and an `X-Requested-With` header. Reusing an already-rotated token revokes the whole session family.
         */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke this session family and clear the cookie */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The authenticated account */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm an email address with a mailed token */
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a password-reset link
         * @description Always answers 202 — account existence is never revealed.
         */
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set a new password with a mailed token
         * @description Consuming the token revokes every live session.
         */
        post: operations["confirmPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/discord": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Begin Discord OAuth (redirects to discord.com) */
        get: operations["discordStart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/discord/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Discord OAuth callback (redirects back to the web app) */
        get: operations["discordCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse or search the catalog
         * @description With `q`, performs ranked fuzzy search. Without it, browses by popularity with optional filters.
         */
        get: operations["listAnime"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anime/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Anime detail with episodes */
        get: operations["getAnime"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seasons/{year}/{season}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Seasonal chart */
        get: operations["getSeason"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Airing schedule for a time window
         * @description Defaults to the next 7 days. The window is capped at 14 days.
         */
        get: operations["getSchedule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterRequest: {
            /** Format: email */
            email: string;
            /** @description 3-20 characters, letters/digits/underscore */
            username: string;
            password: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        TokenRequest: {
            token: string;
        };
        PasswordResetRequest: {
            /** Format: email */
            email: string;
        };
        PasswordResetConfirm: {
            token: string;
            password: string;
        };
        SessionResponse: {
            /** @description Short-lived JWT for the Authorization header */
            access_token: string;
            /** @enum {string} */
            token_type: "Bearer";
            /** @description Access-token lifetime in seconds */
            expires_in: number;
            user: components["schemas"]["UserPrivate"];
        };
        /** @enum {string} */
        Role: "user" | "mod" | "admin";
        UserPrivate: {
            /** Format: int64 */
            id: number;
            email: string;
            username: string;
            avatar_url: string | null;
            bio: string;
            favorite_genres: string[];
            role: components["schemas"]["Role"];
            email_verified: boolean;
            /** Format: date-time */
            created_at: string;
        };
        /** @enum {string} */
        Season: "WINTER" | "SPRING" | "SUMMER" | "FALL";
        /** @enum {string} */
        AiringStatus: "FINISHED" | "RELEASING" | "NOT_YET_RELEASED" | "CANCELLED" | "HIATUS";
        /** @enum {string} */
        Format: "TV" | "TV_SHORT" | "MOVIE" | "SPECIAL" | "OVA" | "ONA" | "MUSIC";
        AnimeSummary: {
            /** Format: int64 */
            id: number;
            /** @description Cosmetic URL segment derived from the title */
            slug: string;
            /** @description Romaji title */
            title: string;
            title_english: string | null;
            cover_image: string | null;
            /** @description Dominant cover color */
            cover_color: string | null;
            format: components["schemas"]["Format"] | null;
            status: components["schemas"]["AiringStatus"];
            season: components["schemas"]["Season"] | null;
            season_year: number | null;
            episodes_count: number | null;
            /** @description AniList community mean */
            average_score: number | null;
            popularity: number;
            genres: string[];
            /** Format: date-time */
            next_airing_at: string | null;
            next_airing_episode: number | null;
        };
        AnimeDetail: components["schemas"]["AnimeSummary"] & {
            anilist_id: number;
            title_native: string | null;
            synonyms: string[];
            /** @description Plain text with newlines; AniList markup stripped. */
            description: string | null;
            banner_image: string | null;
            duration_min: number | null;
            tags: components["schemas"]["Tag"][];
            studios: components["schemas"]["Studio"][];
            episodes: components["schemas"]["Episode"][];
            /** Format: date-time */
            synced_at: string;
        };
        Tag: {
            name: string;
            rank: number;
        };
        Studio: {
            name: string;
            is_main: boolean;
        };
        Episode: {
            number: number;
            title: string | null;
            /** Format: date-time */
            airing_at: string | null;
        };
        ScheduleEntry: {
            anime: components["schemas"]["AnimeSummary"];
            episode: number;
            /** Format: date-time */
            airing_at: string;
        };
        AnimeList: {
            data: components["schemas"]["AnimeSummary"][];
            page: components["schemas"]["PageInfo"];
        };
        SeasonChart: {
            season: components["schemas"]["Season"];
            year: number;
            data: components["schemas"]["AnimeSummary"][];
        };
        ScheduleList: {
            data: components["schemas"]["ScheduleEntry"][];
        };
        PageInfo: {
            page: number;
            per_page: number;
            has_more: boolean;
        };
        ErrorEnvelope: {
            error: {
                /** @description Stable machine-readable code: bad_request, validation_failed, unauthorized, forbidden, not_found, conflict, rate_limited, internal_error, service_unavailable. */
                code: string;
                message: string;
                details?: unknown;
            };
        };
    };
    responses: {
        /** @description Error envelope */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Account created; session established (refresh cookie set) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Session established (refresh cookie set) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New session (refresh cookie rotated) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPrivate"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description Email verified */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description If the account exists */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    confirmPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirm"];
            };
        };
        responses: {
            /** @description Password updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    discordStart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to Discord authorize page */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    discordCallback: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the web app with the session cookie set */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listAnime: {
        parameters: {
            query?: {
                q?: string;
                genre?: string;
                year?: number;
                season?: components["schemas"]["Season"];
                status?: components["schemas"]["AiringStatus"];
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching anime */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimeList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getAnime: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The anime */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimeDetail"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSeason: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: number;
                season: components["schemas"]["Season"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All titles airing in the season, most popular first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonChart"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSchedule: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Episodes airing in the window, soonest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
