/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account with email + password */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in with email + password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the refresh cookie into a fresh session
         * @description Requires the httpOnly refresh cookie and an `X-Requested-With` header. Reusing an already-rotated token revokes the whole session family.
         */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke this session family and clear the cookie */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The authenticated account */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm an email address with a mailed token */
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a password-reset link
         * @description Always answers 202 — account existence is never revealed.
         */
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set a new password with a mailed token
         * @description Consuming the token revokes every live session.
         */
        post: operations["confirmPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/discord": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Begin Discord OAuth (redirects to discord.com) */
        get: operations["discordStart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/discord/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Discord OAuth callback (redirects back to the web app) */
        get: operations["discordCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The authenticated user's anime list */
        get: operations["getMyList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/list/{animeId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                animeId: number;
            };
            cookie?: never;
        };
        /** This user's entry for one anime (404 when untracked) */
        get: operations["getMyListEntry"];
        /** Add or update this anime on the user's list */
        put: operations["upsertMyListEntry"];
        post?: never;
        /** Remove this anime from the user's list */
        delete: operations["deleteMyListEntry"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The authenticated user's favorites */
        get: operations["getMyFavorites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/favorites/{animeId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                animeId: number;
            };
            cookie?: never;
        };
        /** Whether this anime is in the user's favorites */
        get: operations["getFavoriteState"];
        /** Add to favorites */
        put: operations["addFavorite"];
        post?: never;
        /** Remove from favorites */
        delete: operations["removeFavorite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public profile with stats and showcases */
        get: operations["getUserProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit bio, avatar, and favorite genres */
        patch: operations["updateMyProfile"];
        trace?: never;
    };
    "/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a fresh email-verification link */
        post: operations["resendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{username}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        /** Follow counts and whether the caller follows this user */
        get: operations["getFollowState"];
        /** Follow this user */
        put: operations["followUser"];
        post?: never;
        /** Unfollow this user */
        delete: operations["unfollowUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{username}/followers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who follows this user */
        get: operations["listFollowers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{username}/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who this user follows */
        get: operations["listFollowing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Activity from everyone the caller follows */
        get: operations["getMyFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's notifications, newest first */
        get: operations["getMyNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unread notification count (for the bell) */
        get: operations["getUnreadCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/notifications/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark notifications read (specific ids or all) */
        post: operations["markNotificationsRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse or search the catalog
         * @description With `q`, performs ranked fuzzy search. Without it, browses by popularity with optional filters.
         */
        get: operations["listAnime"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anime/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Anime detail with episodes */
        get: operations["getAnime"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anime/{id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reviews for an anime, most helpful first */
        get: operations["listAnimeReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anime/{id}/reviews/mine": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** The caller's review of this anime (404 when none) */
        get: operations["getMyReview"];
        /** Write or edit the caller's review */
        put: operations["upsertMyReview"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{reviewId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewId: number;
            };
            cookie?: never;
        };
        /** One review with its anime */
        get: operations["getReview"];
        put?: never;
        post?: never;
        /** Soft-delete a review (author or moderator) */
        delete: operations["deleteReview"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{reviewId}/helpful": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewId: number;
            };
            cookie?: never;
        };
        get?: never;
        /** Mark a review helpful */
        put: operations["markHelpful"];
        post?: never;
        /** Remove a helpful mark */
        delete: operations["unmarkHelpful"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{username}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reviews written by a user, newest first */
        get: operations["listUserReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anime/{id}/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Discussion index for an anime (series board + episode threads) */
        get: operations["getAnimeThreads"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anime/{id}/threads/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The anime's series board (created on first visit) */
        get: operations["getSeriesThread"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anime/{id}/episodes/{number}/thread": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** An episode's thread with context (created on first visit) */
        get: operations["getEpisodeThread"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/threads/{threadId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: number;
            };
            cookie?: never;
        };
        /** A thread's comments, oldest first (client builds the tree) */
        get: operations["listComments"];
        put?: never;
        /** Add a comment (optionally anchored to a moment) */
        post: operations["postComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Soft-delete a comment (author or moderator); tombstone remains */
        delete: operations["deleteComment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comments/{commentId}/reactions/{emoji}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: number;
                emoji: components["schemas"]["Emoji"];
            };
            cookie?: never;
        };
        get?: never;
        /** React to a comment */
        put: operations["addReaction"];
        post?: never;
        /** Remove a reaction */
        delete: operations["removeReaction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seasons/{year}/{season}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Seasonal chart */
        get: operations["getSeason"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trending Now — recency-weighted, time-decayed
         * @description Ranked by recent Cour activity with exponential time decay (not all-time popularity), lightly blended with AniList's trending signal.
         */
        get: operations["getTrending"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hidden-gems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent, highly-rated, under-watched titles */
        get: operations["getHiddenGems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Taste-based suggestions with explanations */
        get: operations["getMyRecommendations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Airing schedule for a time window
         * @description Defaults to the next 7 days. The window is capped at 14 days.
         */
        get: operations["getSchedule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterRequest: {
            /** Format: email */
            email: string;
            /** @description 3-20 characters, letters/digits/underscore */
            username: string;
            password: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        TokenRequest: {
            token: string;
        };
        PasswordResetRequest: {
            /** Format: email */
            email: string;
        };
        PasswordResetConfirm: {
            token: string;
            password: string;
        };
        SessionResponse: {
            /** @description Short-lived JWT for the Authorization header */
            access_token: string;
            /** @enum {string} */
            token_type: "Bearer";
            /** @description Access-token lifetime in seconds */
            expires_in: number;
            user: components["schemas"]["UserPrivate"];
        };
        /** @enum {string} */
        Role: "user" | "mod" | "admin";
        UserPrivate: {
            /** Format: int64 */
            id: number;
            email: string;
            username: string;
            avatar_url: string | null;
            bio: string;
            favorite_genres: string[];
            role: components["schemas"]["Role"];
            email_verified: boolean;
            /** Format: date-time */
            created_at: string;
        };
        UserProfile: {
            username: string;
            avatar_url: string | null;
            bio: string;
            favorite_genres: string[];
            role: components["schemas"]["Role"];
            /** Format: date-time */
            created_at: string;
            stats: components["schemas"]["ProfileStats"];
            favorites: components["schemas"]["AnimeSummary"][];
            currently_watching: components["schemas"]["WatchingEntry"][];
        };
        ProfileStats: {
            counts: {
                watching: number;
                completed: number;
                planning: number;
                paused: number;
                dropped: number;
            };
            /** @description Mean of 1-10 scores; null until something is rated */
            mean_score: number | null;
            rated_count: number;
            episodes_watched: number;
            genres: {
                genre: string;
                count: number;
            }[];
        };
        WatchingEntry: {
            anime: components["schemas"]["AnimeSummary"];
            progress: number;
        };
        UpdateProfileRequest: {
            bio?: string;
            /** @description http(s) URL; null clears the avatar */
            avatar_url?: string | null;
            favorite_genres?: string[];
        };
        /** @enum {string} */
        ListStatus: "watching" | "completed" | "planning" | "paused" | "dropped";
        ListEntry: {
            /** Format: int64 */
            anime_id: number;
            status: components["schemas"]["ListStatus"];
            score: number | null;
            progress: number;
            /** Format: date */
            started_on: string | null;
            /** Format: date */
            finished_on: string | null;
            /** Format: date-time */
            updated_at: string;
        };
        ListEntryWithAnime: components["schemas"]["ListEntry"] & {
            anime: components["schemas"]["AnimeSummary"];
        };
        MyList: {
            data: components["schemas"]["ListEntryWithAnime"][];
        };
        UpsertListEntryRequest: {
            status: components["schemas"]["ListStatus"];
            /** @description 1-10; 0 clears the score; omitted keeps it */
            score?: number | null;
            progress?: number | null;
            /** Format: date */
            started_on?: string | null;
            /** Format: date */
            finished_on?: string | null;
        };
        FavoritesList: {
            data: components["schemas"]["AnimeSummary"][];
        };
        FavoriteState: {
            favorited: boolean;
        };
        ReviewAuthor: {
            username: string;
            avatar_url: string | null;
        };
        Review: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            anime_id: number;
            author: components["schemas"]["ReviewAuthor"];
            body: string;
            score: number;
            has_spoilers: boolean;
            helpful_count: number;
            /** @description Whether the caller marked it helpful (false when anonymous) */
            voted: boolean;
            is_mine: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ReviewDetail: components["schemas"]["Review"] & {
            anime: components["schemas"]["AnimeSummary"];
        };
        UpsertReviewRequest: {
            body: string;
            score: number;
            /** @default false */
            has_spoilers: boolean;
        };
        ReviewList: {
            data: components["schemas"]["Review"][];
            page: components["schemas"]["PageInfo"];
        };
        UserReviewList: {
            data: components["schemas"]["ReviewDetail"][];
            page: components["schemas"]["PageInfo"];
        };
        HelpfulState: {
            helpful_count: number;
            voted: boolean;
        };
        TrendingList: {
            data: components["schemas"]["AnimeSummary"][];
            /** Format: date-time */
            computed_at: string | null;
        };
        DiscoveryList: {
            data: components["schemas"]["AnimeSummary"][];
        };
        RecommendationItem: {
            anime: components["schemas"]["AnimeSummary"];
            reasons: string[];
        };
        Recommendations: {
            data: components["schemas"]["RecommendationItem"][];
            /** @description True when there was no taste signal and the list falls back to trending + gems */
            cold_start: boolean;
        };
        RelationState: {
            followers: number;
            following: number;
            /** @description Always false for anonymous callers */
            is_following: boolean;
        };
        UserRefList: {
            data: components["schemas"]["ReviewAuthor"][];
        };
        /** @enum {string} */
        ActivityType: "list_add" | "status_change" | "progress" | "completed" | "scored" | "favorite" | "review" | "comment" | "helpful_vote";
        FeedItem: {
            /** Format: int64 */
            id: number;
            actor: components["schemas"]["ReviewAuthor"];
            type: components["schemas"]["ActivityType"];
            anime: components["schemas"]["AnimeSummary"];
            /** Format: int64 */
            ref_id: number | null;
            payload: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
        Feed: {
            data: components["schemas"]["FeedItem"][];
            /**
             * Format: int64
             * @description Pass back as ?cursor= for the next page; null at the end
             */
            next_cursor: number | null;
        };
        /** @enum {string} */
        NotificationType: "comment_reply" | "new_follower" | "episode_aired";
        Notification: {
            /** Format: int64 */
            id: number;
            type: components["schemas"]["NotificationType"];
            actor: components["schemas"]["ReviewAuthor"] | null;
            anime: components["schemas"]["AnimeSummary"] | null;
            /** Format: int64 */
            ref_id: number | null;
            payload: {
                [key: string]: unknown;
            };
            read: boolean;
            /** Format: date-time */
            created_at: string;
        };
        NotificationList: {
            data: components["schemas"]["Notification"][];
            /** Format: int64 */
            next_cursor: number | null;
        };
        UnreadCount: {
            count: number;
        };
        MarkReadRequest: {
            ids?: number[];
            /** @default false */
            all: boolean;
        };
        /** @enum {string} */
        Emoji: "+1" | "heart" | "laugh" | "surprise" | "cry" | "fire";
        Thread: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            anime_id: number;
            /** @enum {string} */
            kind: "series" | "episode";
            comment_count: number;
            /** Format: date-time */
            last_activity_at: string;
        };
        EpisodeThread: {
            thread: components["schemas"]["Thread"];
            anime: components["schemas"]["AnimeSummary"];
            episode: components["schemas"]["Episode"];
        };
        ThreadIndex: {
            series: components["schemas"]["Thread"] | null;
            episodes: {
                number: number;
                /** Format: int64 */
                thread_id: number;
                comment_count: number;
                /** Format: date-time */
                last_activity_at: string;
            }[];
        };
        ReactionCount: {
            emoji: components["schemas"]["Emoji"];
            count: number;
            mine: boolean;
        };
        Comment: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            thread_id: number;
            /** Format: int64 */
            parent_id: number | null;
            author: components["schemas"]["ReviewAuthor"];
            /** @description "[removed]" when deleted */
            body: string;
            /** @description Moment anchor within the episode */
            timestamp_seconds: number | null;
            has_spoilers: boolean;
            deleted: boolean;
            reactions: components["schemas"]["ReactionCount"][];
            /** Format: date-time */
            created_at: string;
        };
        CommentList: {
            data: components["schemas"]["Comment"][];
        };
        PostCommentRequest: {
            body: string;
            /** Format: int64 */
            parent_id?: number | null;
            /** @description Only valid in episode threads */
            timestamp_seconds?: number | null;
            /** @default false */
            has_spoilers: boolean;
        };
        /** @enum {string} */
        Season: "WINTER" | "SPRING" | "SUMMER" | "FALL";
        /** @enum {string} */
        AiringStatus: "FINISHED" | "RELEASING" | "NOT_YET_RELEASED" | "CANCELLED" | "HIATUS";
        /** @enum {string} */
        Format: "TV" | "TV_SHORT" | "MOVIE" | "SPECIAL" | "OVA" | "ONA" | "MUSIC";
        AnimeSummary: {
            /** Format: int64 */
            id: number;
            /** @description Cosmetic URL segment derived from the title */
            slug: string;
            /** @description Romaji title */
            title: string;
            title_english: string | null;
            cover_image: string | null;
            /** @description Dominant cover color */
            cover_color: string | null;
            format: components["schemas"]["Format"] | null;
            status: components["schemas"]["AiringStatus"];
            season: components["schemas"]["Season"] | null;
            season_year: number | null;
            episodes_count: number | null;
            /** @description AniList community mean */
            average_score: number | null;
            popularity: number;
            genres: string[];
            /** Format: date-time */
            next_airing_at: string | null;
            next_airing_episode: number | null;
        };
        AnimeDetail: components["schemas"]["AnimeSummary"] & {
            anilist_id: number;
            title_native: string | null;
            synonyms: string[];
            /** @description Plain text with newlines; AniList markup stripped. */
            description: string | null;
            banner_image: string | null;
            duration_min: number | null;
            tags: components["schemas"]["Tag"][];
            studios: components["schemas"]["Studio"][];
            episodes: components["schemas"]["Episode"][];
            /** Format: date-time */
            synced_at: string;
        };
        Tag: {
            name: string;
            rank: number;
        };
        Studio: {
            name: string;
            is_main: boolean;
        };
        Episode: {
            number: number;
            title: string | null;
            /** Format: date-time */
            airing_at: string | null;
        };
        ScheduleEntry: {
            anime: components["schemas"]["AnimeSummary"];
            episode: number;
            /** Format: date-time */
            airing_at: string;
        };
        AnimeList: {
            data: components["schemas"]["AnimeSummary"][];
            page: components["schemas"]["PageInfo"];
        };
        SeasonChart: {
            season: components["schemas"]["Season"];
            year: number;
            data: components["schemas"]["AnimeSummary"][];
        };
        ScheduleList: {
            data: components["schemas"]["ScheduleEntry"][];
        };
        PageInfo: {
            page: number;
            per_page: number;
            has_more: boolean;
        };
        ErrorEnvelope: {
            error: {
                /** @description Stable machine-readable code: bad_request, validation_failed, unauthorized, forbidden, not_found, conflict, rate_limited, internal_error, service_unavailable. */
                code: string;
                message: string;
                details?: unknown;
            };
        };
    };
    responses: {
        /** @description Error envelope */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Account created; session established (refresh cookie set) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Session established (refresh cookie set) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New session (refresh cookie rotated) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPrivate"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description Email verified */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description If the account exists */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    confirmPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirm"];
            };
        };
        responses: {
            /** @description Password updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    discordStart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to Discord authorize page */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    discordCallback: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the web app with the session cookie set */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getMyList: {
        parameters: {
            query?: {
                status?: components["schemas"]["ListStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List entries, most recently updated first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getMyListEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                animeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The entry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEntry"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    upsertMyListEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                animeId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertListEntryRequest"];
            };
        };
        responses: {
            /** @description The resulting entry (after auto-transitions) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEntry"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteMyListEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                animeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getMyFavorites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Favorites, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoritesList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getFavoriteState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                animeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Favorite state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoriteState"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    addFavorite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                animeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Favorited */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    removeFavorite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                animeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unfavorited */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description The updated account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPrivate"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    resendVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sent (no-op when already verified) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getFollowState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Relation state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationState"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    followUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated relation state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationState"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    unfollowUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated relation state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationState"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listFollowers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Followers, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRefList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listFollowing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Followed users, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRefList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getMyFeed: {
        parameters: {
            query?: {
                cursor?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Feed page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feed"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getMyNotifications: {
        parameters: {
            query?: {
                cursor?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notification page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getUnreadCount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Count */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnreadCount"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    markNotificationsRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkReadRequest"];
            };
        };
        responses: {
            /** @description Marked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listAnime: {
        parameters: {
            query?: {
                q?: string;
                genre?: string;
                year?: number;
                season?: components["schemas"]["Season"];
                status?: components["schemas"]["AiringStatus"];
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching anime */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimeList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getAnime: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The anime */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimeDetail"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listAnimeReviews: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reviews */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getMyReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The review */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    upsertMyReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertReviewRequest"];
            };
        };
        responses: {
            /** @description The saved review */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The review */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewDetail"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    markHelpful: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New vote state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HelpfulState"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    unmarkHelpful: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New vote state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HelpfulState"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listUserReviews: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reviews with their anime */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserReviewList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getAnimeThreads: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Existing threads and their sizes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadIndex"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSeriesThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The thread */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thread"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getEpisodeThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Thread + episode + anime */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeThread"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listComments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comments with authors and reactions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    postComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostCommentRequest"];
            };
        };
        responses: {
            /** @description The comment */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    addReaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: number;
                emoji: components["schemas"]["Emoji"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reacted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    removeReaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: number;
                emoji: components["schemas"]["Emoji"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getSeason: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: number;
                season: components["schemas"]["Season"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All titles airing in the season, most popular first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonChart"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getTrending: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ranked titles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendingList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getHiddenGems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The gems rail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getMyRecommendations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Personalized picks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recommendations"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSchedule: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Episodes airing in the window, soonest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
