/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/anime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse or search the catalog
         * @description With `q`, performs ranked fuzzy search. Without it, browses by popularity with optional filters.
         */
        get: operations["listAnime"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anime/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Anime detail with episodes */
        get: operations["getAnime"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seasons/{year}/{season}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Seasonal chart */
        get: operations["getSeason"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Airing schedule for a time window
         * @description Defaults to the next 7 days. The window is capped at 14 days.
         */
        get: operations["getSchedule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Season: "WINTER" | "SPRING" | "SUMMER" | "FALL";
        /** @enum {string} */
        AiringStatus: "FINISHED" | "RELEASING" | "NOT_YET_RELEASED" | "CANCELLED" | "HIATUS";
        /** @enum {string} */
        Format: "TV" | "TV_SHORT" | "MOVIE" | "SPECIAL" | "OVA" | "ONA" | "MUSIC";
        AnimeSummary: {
            /** Format: int64 */
            id: number;
            /** @description Cosmetic URL segment derived from the title */
            slug: string;
            /** @description Romaji title */
            title: string;
            title_english: string | null;
            cover_image: string | null;
            /** @description Dominant cover color */
            cover_color: string | null;
            format: components["schemas"]["Format"] | null;
            status: components["schemas"]["AiringStatus"];
            season: components["schemas"]["Season"] | null;
            season_year: number | null;
            episodes_count: number | null;
            /** @description AniList community mean */
            average_score: number | null;
            popularity: number;
            genres: string[];
            /** Format: date-time */
            next_airing_at: string | null;
            next_airing_episode: number | null;
        };
        AnimeDetail: components["schemas"]["AnimeSummary"] & {
            anilist_id: number;
            title_native: string | null;
            synonyms: string[];
            /** @description Plain text with newlines; AniList markup stripped. */
            description: string | null;
            banner_image: string | null;
            duration_min: number | null;
            tags: components["schemas"]["Tag"][];
            studios: components["schemas"]["Studio"][];
            episodes: components["schemas"]["Episode"][];
            /** Format: date-time */
            synced_at: string;
        };
        Tag: {
            name: string;
            rank: number;
        };
        Studio: {
            name: string;
            is_main: boolean;
        };
        Episode: {
            number: number;
            title: string | null;
            /** Format: date-time */
            airing_at: string | null;
        };
        ScheduleEntry: {
            anime: components["schemas"]["AnimeSummary"];
            episode: number;
            /** Format: date-time */
            airing_at: string;
        };
        AnimeList: {
            data: components["schemas"]["AnimeSummary"][];
            page: components["schemas"]["PageInfo"];
        };
        SeasonChart: {
            season: components["schemas"]["Season"];
            year: number;
            data: components["schemas"]["AnimeSummary"][];
        };
        ScheduleList: {
            data: components["schemas"]["ScheduleEntry"][];
        };
        PageInfo: {
            page: number;
            per_page: number;
            has_more: boolean;
        };
        ErrorEnvelope: {
            error: {
                /** @description Stable machine-readable code: bad_request, validation_failed, unauthorized, forbidden, not_found, conflict, rate_limited, internal_error, service_unavailable. */
                code: string;
                message: string;
                details?: unknown;
            };
        };
    };
    responses: {
        /** @description Error envelope */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAnime: {
        parameters: {
            query?: {
                q?: string;
                genre?: string;
                year?: number;
                season?: components["schemas"]["Season"];
                status?: components["schemas"]["AiringStatus"];
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching anime */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimeList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getAnime: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The anime */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimeDetail"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSeason: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: number;
                season: components["schemas"]["Season"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All titles airing in the season, most popular first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonChart"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSchedule: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Episodes airing in the window, soonest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
