// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: anime.sql

package sqlcgen

import (
	"context"
	"time"
)

const browseAnime = `-- name: BrowseAnime :many
SELECT id, anilist_id, title_romaji, title_english, title_native, synonyms, description, format, status, season, season_year, episodes_count, duration_min, genres, tags, studios, cover_image, cover_color, banner_image, average_score, popularity, anilist_trending, is_adult, next_airing_at, next_airing_episode, synced_at, created_at, updated_at, search_doc, mal_id FROM anime
WHERE is_adult = FALSE
  AND ($3::text IS NULL OR $3 = ANY(genres))
  AND ($4::int IS NULL OR season_year = $4)
  AND ($5::anime_season IS NULL OR season = $5)
  AND ($6::anime_status IS NULL OR status = $6)
ORDER BY popularity DESC
LIMIT $1 OFFSET $2
`

type BrowseAnimeParams struct {
	Limit      int32
	Offset     int32
	Genre      *string
	SeasonYear *int32
	Season     *AnimeSeason
	Status     *AnimeStatus
}

func (q *Queries) BrowseAnime(ctx context.Context, arg BrowseAnimeParams) ([]Anime, error) {
	rows, err := q.db.Query(ctx, browseAnime,
		arg.Limit,
		arg.Offset,
		arg.Genre,
		arg.SeasonYear,
		arg.Season,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Anime
	for rows.Next() {
		var i Anime
		if err := rows.Scan(
			&i.ID,
			&i.AnilistID,
			&i.TitleRomaji,
			&i.TitleEnglish,
			&i.TitleNative,
			&i.Synonyms,
			&i.Description,
			&i.Format,
			&i.Status,
			&i.Season,
			&i.SeasonYear,
			&i.EpisodesCount,
			&i.DurationMin,
			&i.Genres,
			&i.Tags,
			&i.Studios,
			&i.CoverImage,
			&i.CoverColor,
			&i.BannerImage,
			&i.AverageScore,
			&i.Popularity,
			&i.AnilistTrending,
			&i.IsAdult,
			&i.NextAiringAt,
			&i.NextAiringEpisode,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchDoc,
			&i.MalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ensureEpisodes = `-- name: EnsureEpisodes :exec
INSERT INTO episodes (anime_id, number)
SELECT $1, generate_series(1, $2::int)
ON CONFLICT (anime_id, number) DO NOTHING
`

type EnsureEpisodesParams struct {
	AnimeID int64
	Column2 int32
}

// Create bare rows 1..N for an anime so episode threads always have an
// anchor; airing sync fills in air times later.
func (q *Queries) EnsureEpisodes(ctx context.Context, arg EnsureEpisodesParams) error {
	_, err := q.db.Exec(ctx, ensureEpisodes, arg.AnimeID, arg.Column2)
	return err
}

const getAnime = `-- name: GetAnime :one
SELECT id, anilist_id, title_romaji, title_english, title_native, synonyms, description, format, status, season, season_year, episodes_count, duration_min, genres, tags, studios, cover_image, cover_color, banner_image, average_score, popularity, anilist_trending, is_adult, next_airing_at, next_airing_episode, synced_at, created_at, updated_at, search_doc, mal_id FROM anime WHERE id = $1
`

func (q *Queries) GetAnime(ctx context.Context, id int64) (Anime, error) {
	row := q.db.QueryRow(ctx, getAnime, id)
	var i Anime
	err := row.Scan(
		&i.ID,
		&i.AnilistID,
		&i.TitleRomaji,
		&i.TitleEnglish,
		&i.TitleNative,
		&i.Synonyms,
		&i.Description,
		&i.Format,
		&i.Status,
		&i.Season,
		&i.SeasonYear,
		&i.EpisodesCount,
		&i.DurationMin,
		&i.Genres,
		&i.Tags,
		&i.Studios,
		&i.CoverImage,
		&i.CoverColor,
		&i.BannerImage,
		&i.AverageScore,
		&i.Popularity,
		&i.AnilistTrending,
		&i.IsAdult,
		&i.NextAiringAt,
		&i.NextAiringEpisode,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchDoc,
		&i.MalID,
	)
	return i, err
}

const getAnimeByAniListID = `-- name: GetAnimeByAniListID :one
SELECT id, anilist_id, title_romaji, title_english, title_native, synonyms, description, format, status, season, season_year, episodes_count, duration_min, genres, tags, studios, cover_image, cover_color, banner_image, average_score, popularity, anilist_trending, is_adult, next_airing_at, next_airing_episode, synced_at, created_at, updated_at, search_doc, mal_id FROM anime WHERE anilist_id = $1
`

func (q *Queries) GetAnimeByAniListID(ctx context.Context, anilistID int32) (Anime, error) {
	row := q.db.QueryRow(ctx, getAnimeByAniListID, anilistID)
	var i Anime
	err := row.Scan(
		&i.ID,
		&i.AnilistID,
		&i.TitleRomaji,
		&i.TitleEnglish,
		&i.TitleNative,
		&i.Synonyms,
		&i.Description,
		&i.Format,
		&i.Status,
		&i.Season,
		&i.SeasonYear,
		&i.EpisodesCount,
		&i.DurationMin,
		&i.Genres,
		&i.Tags,
		&i.Studios,
		&i.CoverImage,
		&i.CoverColor,
		&i.BannerImage,
		&i.AverageScore,
		&i.Popularity,
		&i.AnilistTrending,
		&i.IsAdult,
		&i.NextAiringAt,
		&i.NextAiringEpisode,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchDoc,
		&i.MalID,
	)
	return i, err
}

const listAiringBetween = `-- name: ListAiringBetween :many
SELECT episodes.id, episodes.anime_id, episodes.number, episodes.title, episodes.airing_at, episodes.created_at, anime.id, anime.anilist_id, anime.title_romaji, anime.title_english, anime.title_native, anime.synonyms, anime.description, anime.format, anime.status, anime.season, anime.season_year, anime.episodes_count, anime.duration_min, anime.genres, anime.tags, anime.studios, anime.cover_image, anime.cover_color, anime.banner_image, anime.average_score, anime.popularity, anime.anilist_trending, anime.is_adult, anime.next_airing_at, anime.next_airing_episode, anime.synced_at, anime.created_at, anime.updated_at, anime.search_doc, anime.mal_id
FROM episodes
JOIN anime ON anime.id = episodes.anime_id
WHERE episodes.airing_at >= $1 AND episodes.airing_at < $2 AND anime.is_adult = FALSE
ORDER BY episodes.airing_at
`

type ListAiringBetweenParams struct {
	AiringAt   *time.Time
	AiringAt_2 *time.Time
}

type ListAiringBetweenRow struct {
	Episode Episode
	Anime   Anime
}

func (q *Queries) ListAiringBetween(ctx context.Context, arg ListAiringBetweenParams) ([]ListAiringBetweenRow, error) {
	rows, err := q.db.Query(ctx, listAiringBetween, arg.AiringAt, arg.AiringAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAiringBetweenRow
	for rows.Next() {
		var i ListAiringBetweenRow
		if err := rows.Scan(
			&i.Episode.ID,
			&i.Episode.AnimeID,
			&i.Episode.Number,
			&i.Episode.Title,
			&i.Episode.AiringAt,
			&i.Episode.CreatedAt,
			&i.Anime.ID,
			&i.Anime.AnilistID,
			&i.Anime.TitleRomaji,
			&i.Anime.TitleEnglish,
			&i.Anime.TitleNative,
			&i.Anime.Synonyms,
			&i.Anime.Description,
			&i.Anime.Format,
			&i.Anime.Status,
			&i.Anime.Season,
			&i.Anime.SeasonYear,
			&i.Anime.EpisodesCount,
			&i.Anime.DurationMin,
			&i.Anime.Genres,
			&i.Anime.Tags,
			&i.Anime.Studios,
			&i.Anime.CoverImage,
			&i.Anime.CoverColor,
			&i.Anime.BannerImage,
			&i.Anime.AverageScore,
			&i.Anime.Popularity,
			&i.Anime.AnilistTrending,
			&i.Anime.IsAdult,
			&i.Anime.NextAiringAt,
			&i.Anime.NextAiringEpisode,
			&i.Anime.SyncedAt,
			&i.Anime.CreatedAt,
			&i.Anime.UpdatedAt,
			&i.Anime.SearchDoc,
			&i.Anime.MalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnimeByIDs = `-- name: ListAnimeByIDs :many
SELECT id, anilist_id, title_romaji, title_english, title_native, synonyms, description, format, status, season, season_year, episodes_count, duration_min, genres, tags, studios, cover_image, cover_color, banner_image, average_score, popularity, anilist_trending, is_adult, next_airing_at, next_airing_episode, synced_at, created_at, updated_at, search_doc, mal_id FROM anime WHERE id = ANY($1::bigint[])
`

func (q *Queries) ListAnimeByIDs(ctx context.Context, dollar_1 []int64) ([]Anime, error) {
	rows, err := q.db.Query(ctx, listAnimeByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Anime
	for rows.Next() {
		var i Anime
		if err := rows.Scan(
			&i.ID,
			&i.AnilistID,
			&i.TitleRomaji,
			&i.TitleEnglish,
			&i.TitleNative,
			&i.Synonyms,
			&i.Description,
			&i.Format,
			&i.Status,
			&i.Season,
			&i.SeasonYear,
			&i.EpisodesCount,
			&i.DurationMin,
			&i.Genres,
			&i.Tags,
			&i.Studios,
			&i.CoverImage,
			&i.CoverColor,
			&i.BannerImage,
			&i.AverageScore,
			&i.Popularity,
			&i.AnilistTrending,
			&i.IsAdult,
			&i.NextAiringAt,
			&i.NextAiringEpisode,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchDoc,
			&i.MalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodes = `-- name: ListEpisodes :many
SELECT id, anime_id, number, title, airing_at, created_at FROM episodes WHERE anime_id = $1 ORDER BY number
`

func (q *Queries) ListEpisodes(ctx context.Context, animeID int64) ([]Episode, error) {
	rows, err := q.db.Query(ctx, listEpisodes, animeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Episode
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.AnimeID,
			&i.Number,
			&i.Title,
			&i.AiringAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleasingAnime = `-- name: ListReleasingAnime :many
SELECT id, anilist_id FROM anime WHERE status = 'RELEASING'
`

type ListReleasingAnimeRow struct {
	ID        int64
	AnilistID int32
}

func (q *Queries) ListReleasingAnime(ctx context.Context) ([]ListReleasingAnimeRow, error) {
	rows, err := q.db.Query(ctx, listReleasingAnime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReleasingAnimeRow
	for rows.Next() {
		var i ListReleasingAnimeRow
		if err := rows.Scan(&i.ID, &i.AnilistID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeason = `-- name: ListSeason :many
SELECT id, anilist_id, title_romaji, title_english, title_native, synonyms, description, format, status, season, season_year, episodes_count, duration_min, genres, tags, studios, cover_image, cover_color, banner_image, average_score, popularity, anilist_trending, is_adult, next_airing_at, next_airing_episode, synced_at, created_at, updated_at, search_doc, mal_id FROM anime
WHERE season = $1 AND season_year = $2 AND is_adult = FALSE
ORDER BY popularity DESC
LIMIT $3
`

type ListSeasonParams struct {
	Season     *AnimeSeason
	SeasonYear *int32
	Limit      int32
}

func (q *Queries) ListSeason(ctx context.Context, arg ListSeasonParams) ([]Anime, error) {
	rows, err := q.db.Query(ctx, listSeason, arg.Season, arg.SeasonYear, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Anime
	for rows.Next() {
		var i Anime
		if err := rows.Scan(
			&i.ID,
			&i.AnilistID,
			&i.TitleRomaji,
			&i.TitleEnglish,
			&i.TitleNative,
			&i.Synonyms,
			&i.Description,
			&i.Format,
			&i.Status,
			&i.Season,
			&i.SeasonYear,
			&i.EpisodesCount,
			&i.DurationMin,
			&i.Genres,
			&i.Tags,
			&i.Studios,
			&i.CoverImage,
			&i.CoverColor,
			&i.BannerImage,
			&i.AverageScore,
			&i.Popularity,
			&i.AnilistTrending,
			&i.IsAdult,
			&i.NextAiringAt,
			&i.NextAiringEpisode,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchDoc,
			&i.MalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAnime = `-- name: SearchAnime :many
SELECT anime.id, anime.anilist_id, anime.title_romaji, anime.title_english, anime.title_native, anime.synonyms, anime.description, anime.format, anime.status, anime.season, anime.season_year, anime.episodes_count, anime.duration_min, anime.genres, anime.tags, anime.studios, anime.cover_image, anime.cover_color, anime.banner_image, anime.average_score, anime.popularity, anime.anilist_trending, anime.is_adult, anime.next_airing_at, anime.next_airing_episode, anime.synced_at, anime.created_at, anime.updated_at, anime.search_doc, anime.mal_id,
  GREATEST(
    ts_rank(search_doc, websearch_to_tsquery('simple', $2::text)),
    word_similarity($2, title_romaji),
    word_similarity($2, coalesce(title_english, ''))
  )::float8 AS rank
FROM anime
WHERE is_adult = FALSE
  AND (
    search_doc @@ websearch_to_tsquery('simple', $2)
    OR $2 <% title_romaji
    OR $2 <% coalesce(title_english, '')
  )
ORDER BY rank DESC, popularity DESC
LIMIT $1
`

type SearchAnimeParams struct {
	Limit int32
	Query string
}

type SearchAnimeRow struct {
	Anime Anime
	Rank  float64
}

// Blended full-text + trigram rank: FTS matches word queries; WORD
// similarity (<%) rescues typos — it compares the query against the
// best-matching word, so "friren" finds "Sousou no Frieren" even though
// whole-title similarity would be far below threshold.
func (q *Queries) SearchAnime(ctx context.Context, arg SearchAnimeParams) ([]SearchAnimeRow, error) {
	rows, err := q.db.Query(ctx, searchAnime, arg.Limit, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAnimeRow
	for rows.Next() {
		var i SearchAnimeRow
		if err := rows.Scan(
			&i.Anime.ID,
			&i.Anime.AnilistID,
			&i.Anime.TitleRomaji,
			&i.Anime.TitleEnglish,
			&i.Anime.TitleNative,
			&i.Anime.Synonyms,
			&i.Anime.Description,
			&i.Anime.Format,
			&i.Anime.Status,
			&i.Anime.Season,
			&i.Anime.SeasonYear,
			&i.Anime.EpisodesCount,
			&i.Anime.DurationMin,
			&i.Anime.Genres,
			&i.Anime.Tags,
			&i.Anime.Studios,
			&i.Anime.CoverImage,
			&i.Anime.CoverColor,
			&i.Anime.BannerImage,
			&i.Anime.AverageScore,
			&i.Anime.Popularity,
			&i.Anime.AnilistTrending,
			&i.Anime.IsAdult,
			&i.Anime.NextAiringAt,
			&i.Anime.NextAiringEpisode,
			&i.Anime.SyncedAt,
			&i.Anime.CreatedAt,
			&i.Anime.UpdatedAt,
			&i.Anime.SearchDoc,
			&i.Anime.MalID,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAnime = `-- name: UpsertAnime :one
INSERT INTO anime (
  anilist_id, title_romaji, title_english, title_native, synonyms, description,
  format, status, season, season_year, episodes_count, duration_min, genres,
  tags, studios, cover_image, cover_color, banner_image, average_score,
  popularity, anilist_trending, is_adult, next_airing_at, next_airing_episode,
  mal_id, synced_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17,
  $18, $19, $20, $21, $22, $23, $24, $25, now()
)
ON CONFLICT (anilist_id) DO UPDATE SET
  title_romaji = EXCLUDED.title_romaji,
  title_english = EXCLUDED.title_english,
  title_native = EXCLUDED.title_native,
  synonyms = EXCLUDED.synonyms,
  description = EXCLUDED.description,
  format = EXCLUDED.format,
  status = EXCLUDED.status,
  season = EXCLUDED.season,
  season_year = EXCLUDED.season_year,
  episodes_count = EXCLUDED.episodes_count,
  duration_min = EXCLUDED.duration_min,
  genres = EXCLUDED.genres,
  tags = EXCLUDED.tags,
  studios = EXCLUDED.studios,
  cover_image = EXCLUDED.cover_image,
  cover_color = EXCLUDED.cover_color,
  banner_image = EXCLUDED.banner_image,
  average_score = EXCLUDED.average_score,
  popularity = EXCLUDED.popularity,
  anilist_trending = EXCLUDED.anilist_trending,
  is_adult = EXCLUDED.is_adult,
  next_airing_at = EXCLUDED.next_airing_at,
  next_airing_episode = EXCLUDED.next_airing_episode,
  mal_id = EXCLUDED.mal_id,
  synced_at = now()
RETURNING id
`

type UpsertAnimeParams struct {
	AnilistID         int32
	TitleRomaji       string
	TitleEnglish      *string
	TitleNative       *string
	Synonyms          []string
	Description       *string
	Format            *AnimeFormat
	Status            AnimeStatus
	Season            *AnimeSeason
	SeasonYear        *int32
	EpisodesCount     *int32
	DurationMin       *int32
	Genres            []string
	Tags              []byte
	Studios           []byte
	CoverImage        *string
	CoverColor        *string
	BannerImage       *string
	AverageScore      *int32
	Popularity        int32
	AnilistTrending   int32
	IsAdult           bool
	NextAiringAt      *time.Time
	NextAiringEpisode *int32
	MalID             *int32
}

func (q *Queries) UpsertAnime(ctx context.Context, arg UpsertAnimeParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertAnime,
		arg.AnilistID,
		arg.TitleRomaji,
		arg.TitleEnglish,
		arg.TitleNative,
		arg.Synonyms,
		arg.Description,
		arg.Format,
		arg.Status,
		arg.Season,
		arg.SeasonYear,
		arg.EpisodesCount,
		arg.DurationMin,
		arg.Genres,
		arg.Tags,
		arg.Studios,
		arg.CoverImage,
		arg.CoverColor,
		arg.BannerImage,
		arg.AverageScore,
		arg.Popularity,
		arg.AnilistTrending,
		arg.IsAdult,
		arg.NextAiringAt,
		arg.NextAiringEpisode,
		arg.MalID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertEpisode = `-- name: UpsertEpisode :exec
INSERT INTO episodes (anime_id, number, title, airing_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (anime_id, number) DO UPDATE SET
  title = COALESCE(EXCLUDED.title, episodes.title),
  airing_at = COALESCE(EXCLUDED.airing_at, episodes.airing_at)
`

type UpsertEpisodeParams struct {
	AnimeID  int64
	Number   int32
	Title    *string
	AiringAt *time.Time
}

func (q *Queries) UpsertEpisode(ctx context.Context, arg UpsertEpisodeParams) error {
	_, err := q.db.Exec(ctx, upsertEpisode,
		arg.AnimeID,
		arg.Number,
		arg.Title,
		arg.AiringAt,
	)
	return err
}
