// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeEmailToken = `-- name: ConsumeEmailToken :one
UPDATE email_tokens SET used_at = now()
WHERE token_hash = $1 AND purpose = $2 AND used_at IS NULL AND expires_at > now()
RETURNING id, user_id, purpose, token_hash, expires_at, used_at, created_at
`

type ConsumeEmailTokenParams struct {
	TokenHash []byte
	Purpose   EmailTokenPurpose
}

// Atomically claim an unused, unexpired token; returns it or no rows.
func (q *Queries) ConsumeEmailToken(ctx context.Context, arg ConsumeEmailTokenParams) (EmailToken, error) {
	row := q.db.QueryRow(ctx, consumeEmailToken, arg.TokenHash, arg.Purpose)
	var i EmailToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :execrows
DELETE FROM refresh_tokens WHERE expires_at < now() - interval '7 days'
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, family_id, token_hash, expires_at, used_at, revoked_at, created_at FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertEmailToken = `-- name: InsertEmailToken :exec
INSERT INTO email_tokens (user_id, purpose, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertEmailTokenParams struct {
	UserID    int64
	Purpose   EmailTokenPurpose
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) InsertEmailToken(ctx context.Context, arg InsertEmailTokenParams) error {
	_, err := q.db.Exec(ctx, insertEmailToken,
		arg.UserID,
		arg.Purpose,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO refresh_tokens (user_id, family_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertRefreshTokenParams struct {
	UserID    int64
	FamilyID  uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken,
		arg.UserID,
		arg.FamilyID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :exec
UPDATE refresh_tokens SET used_at = now() WHERE id = $1
`

func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markRefreshTokenUsed, id)
	return err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshFamily = `-- name: RevokeRefreshFamily :exec
UPDATE refresh_tokens SET revoked_at = now()
WHERE family_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshFamily(ctx context.Context, familyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshFamily, familyID)
	return err
}
