// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discovery.sql

package sqlcgen

import (
	"context"
	"time"
)

const activitySignals = `-- name: ActivitySignals :many
SELECT activities.anime_id, activities.type, COUNT(*)::bigint AS count
FROM activities
WHERE activities.anime_id = ANY($1::bigint[])
  AND activities.created_at > $2
GROUP BY activities.anime_id, activities.type
`

type ActivitySignalsParams struct {
	AnimeIds []int64
	Since    time.Time
}

type ActivitySignalsRow struct {
	AnimeID *int64
	Type    ActivityType
	Count   int64
}

// Per-title, per-type activity counts inside the trending window — the
// "why" behind a rank (§M3.8 explained trending).
func (q *Queries) ActivitySignals(ctx context.Context, arg ActivitySignalsParams) ([]ActivitySignalsRow, error) {
	rows, err := q.db.Query(ctx, activitySignals, arg.AnimeIds, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivitySignalsRow
	for rows.Next() {
		var i ActivitySignalsRow
		if err := rows.Scan(&i.AnimeID, &i.Type, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const favoriteNeighborIDs = `-- name: FavoriteNeighborIDs :many

SELECT DISTINCT favorites.user_id FROM favorites
WHERE favorites.anime_id = ANY($1::bigint[]) AND favorites.user_id <> $2
LIMIT 200
`

type FavoriteNeighborIDsParams struct {
	Column1 []int64
	UserID  int64
}

// Taste-neighbor discovery is split into favorites/high-score halves (the
// Go layer unions them) because sqlc's analyzer can't see through derived
// tables over UNIONs.
func (q *Queries) FavoriteNeighborIDs(ctx context.Context, arg FavoriteNeighborIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, favoriteNeighborIDs, arg.Column1, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const favoriteRowsForUsers = `-- name: FavoriteRowsForUsers :many
SELECT favorites.user_id, favorites.anime_id FROM favorites
WHERE favorites.user_id = ANY($1::bigint[])
`

type FavoriteRowsForUsersRow struct {
	UserID  int64
	AnimeID int64
}

func (q *Queries) FavoriteRowsForUsers(ctx context.Context, dollar_1 []int64) ([]FavoriteRowsForUsersRow, error) {
	rows, err := q.db.Query(ctx, favoriteRowsForUsers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FavoriteRowsForUsersRow
	for rows.Next() {
		var i FavoriteRowsForUsersRow
		if err := rows.Scan(&i.UserID, &i.AnimeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const followeesOnList = `-- name: FolloweesOnList :many
SELECT le.anime_id, u.username, le.status
FROM list_entries le
JOIN follows f ON f.followee_id = le.user_id
JOIN users u ON u.id = le.user_id
WHERE f.follower_id = $1
  AND le.anime_id = ANY($2::bigint[])
  AND le.status IN ('watching', 'completed')
ORDER BY le.updated_at DESC
`

type FolloweesOnListParams struct {
	UserID   int64
	AnimeIds []int64
}

type FolloweesOnListRow struct {
	AnimeID  int64
	Username string
	Status   ListStatus
}

// Which of the viewer's followees have these titles on their list — the
// social half of "why is this trending, for me".
func (q *Queries) FolloweesOnList(ctx context.Context, arg FolloweesOnListParams) ([]FolloweesOnListRow, error) {
	rows, err := q.db.Query(ctx, followeesOnList, arg.UserID, arg.AnimeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FolloweesOnListRow
	for rows.Next() {
		var i FolloweesOnListRow
		if err := rows.Scan(&i.AnimeID, &i.Username, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hiddenGems = `-- name: HiddenGems :many
SELECT anime.id, anime.anilist_id, anime.title_romaji, anime.title_english, anime.title_native, anime.synonyms, anime.description, anime.format, anime.status, anime.season, anime.season_year, anime.episodes_count, anime.duration_min, anime.genres, anime.tags, anime.studios, anime.cover_image, anime.cover_color, anime.banner_image, anime.average_score, anime.popularity, anime.anilist_trending, anime.is_adult, anime.next_airing_at, anime.next_airing_episode, anime.synced_at, anime.created_at, anime.updated_at, anime.search_doc, anime.mal_id FROM anime
WHERE anime.season_year >= $1
  AND anime.is_adult = FALSE
  AND anime.format <> 'MUSIC'
  AND anime.average_score IS NOT NULL
  AND anime.popularity >= 100 -- floor: below this, scores are noise
  AND anime.average_score >= $2
  AND anime.popularity <= (
    SELECT percentile_cont(0.35) WITHIN GROUP (ORDER BY pool.popularity)
    FROM anime pool
    WHERE pool.season_year >= $1
      AND pool.is_adult = FALSE
      AND pool.average_score IS NOT NULL
      AND pool.popularity >= 100
  )
ORDER BY
  anime.average_score
    - CASE anime.format
        WHEN 'TV' THEN 0
        WHEN 'MOVIE' THEN 0
        WHEN 'ONA' THEN 3
        ELSE 6
      END DESC,
  anime.popularity ASC
LIMIT $3
`

type HiddenGemsParams struct {
	SeasonYear   *int32
	AverageScore *int32
	Limit        int32
}

// Recent, well-rated, under-watched: the deliberate inversion of the
// popularity bias. The percentile subquery keeps "low popularity" relative
// to the current catalog rather than a magic constant. Music videos never
// qualify, and the ranking docks shorts/OVAs/specials a few points so a
// 12-episode TV gem outranks a 5-minute special with the same score
// (§M3.8: the rail used to be half specials).
func (q *Queries) HiddenGems(ctx context.Context, arg HiddenGemsParams) ([]Anime, error) {
	rows, err := q.db.Query(ctx, hiddenGems, arg.SeasonYear, arg.AverageScore, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Anime
	for rows.Next() {
		var i Anime
		if err := rows.Scan(
			&i.ID,
			&i.AnilistID,
			&i.TitleRomaji,
			&i.TitleEnglish,
			&i.TitleNative,
			&i.Synonyms,
			&i.Description,
			&i.Format,
			&i.Status,
			&i.Season,
			&i.SeasonYear,
			&i.EpisodesCount,
			&i.DurationMin,
			&i.Genres,
			&i.Tags,
			&i.Studios,
			&i.CoverImage,
			&i.CoverColor,
			&i.BannerImage,
			&i.AverageScore,
			&i.Popularity,
			&i.AnilistTrending,
			&i.IsAdult,
			&i.NextAiringAt,
			&i.NextAiringEpisode,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchDoc,
			&i.MalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const highScoreNeighborIDs = `-- name: HighScoreNeighborIDs :many
SELECT DISTINCT list_entries.user_id FROM list_entries
WHERE list_entries.anime_id = ANY($1::bigint[])
  AND list_entries.score >= 8
  AND list_entries.user_id <> $2
LIMIT 200
`

type HighScoreNeighborIDsParams struct {
	Column1 []int64
	UserID  int64
}

func (q *Queries) HighScoreNeighborIDs(ctx context.Context, arg HighScoreNeighborIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, highScoreNeighborIDs, arg.Column1, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const highScoreRowsForUsers = `-- name: HighScoreRowsForUsers :many
SELECT list_entries.user_id, list_entries.anime_id FROM list_entries
WHERE list_entries.user_id = ANY($1::bigint[]) AND list_entries.score >= 8
`

type HighScoreRowsForUsersRow struct {
	UserID  int64
	AnimeID int64
}

func (q *Queries) HighScoreRowsForUsers(ctx context.Context, dollar_1 []int64) ([]HighScoreRowsForUsersRow, error) {
	rows, err := q.db.Query(ctx, highScoreRowsForUsers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HighScoreRowsForUsersRow
	for rows.Next() {
		var i HighScoreRowsForUsersRow
		if err := rows.Scan(&i.UserID, &i.AnimeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTrendingScore = `-- name: InsertTrendingScore :exec
INSERT INTO trending_scores (anime_id, score, rank, computed_at)
VALUES ($1, $2, $3, $4)
`

type InsertTrendingScoreParams struct {
	AnimeID    int64
	Score      float64
	Rank       int32
	ComputedAt time.Time
}

func (q *Queries) InsertTrendingScore(ctx context.Context, arg InsertTrendingScoreParams) error {
	_, err := q.db.Exec(ctx, insertTrendingScore,
		arg.AnimeID,
		arg.Score,
		arg.Rank,
		arg.ComputedAt,
	)
	return err
}

const neighborSignals = `-- name: NeighborSignals :many
SELECT le.user_id, le.anime_id, le.status, le.score, le.updated_at
FROM list_entries le
WHERE le.user_id = ANY($1::bigint[])
  AND (le.status = 'watching' OR (le.score >= 8 AND le.updated_at > $2))
  AND le.anime_id NOT IN (
    SELECT mine.anime_id FROM list_entries mine WHERE mine.user_id = $3
  )
`

type NeighborSignalsParams struct {
	Column1   []int64
	UpdatedAt time.Time
	UserID    int64
}

type NeighborSignalsRow struct {
	UserID    int64
	AnimeID   int64
	Status    ListStatus
	Score     *int16
	UpdatedAt time.Time
}

// What the chosen neighbors are watching now or rated highly recently,
// excluding anime already on the caller's list.
func (q *Queries) NeighborSignals(ctx context.Context, arg NeighborSignalsParams) ([]NeighborSignalsRow, error) {
	rows, err := q.db.Query(ctx, neighborSignals, arg.Column1, arg.UpdatedAt, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NeighborSignalsRow
	for rows.Next() {
		var i NeighborSignalsRow
		if err := rows.Scan(
			&i.UserID,
			&i.AnimeID,
			&i.Status,
			&i.Score,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentAnimeActivity = `-- name: RecentAnimeActivity :many
SELECT anime_id, type, created_at
FROM activities
WHERE created_at > $1 AND anime_id IS NOT NULL
`

type RecentAnimeActivityRow struct {
	AnimeID   *int64
	Type      ActivityType
	CreatedAt time.Time
}

// Raw signal for the trending recompute: every anime-linked activity in the
// window. Decay math happens in Go where it's unit-testable.
func (q *Queries) RecentAnimeActivity(ctx context.Context, createdAt time.Time) ([]RecentAnimeActivityRow, error) {
	rows, err := q.db.Query(ctx, recentAnimeActivity, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentAnimeActivityRow
	for rows.Next() {
		var i RecentAnimeActivityRow
		if err := rows.Scan(&i.AnimeID, &i.Type, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceTrendingScores = `-- name: ReplaceTrendingScores :exec
DELETE FROM trending_scores
`

func (q *Queries) ReplaceTrendingScores(ctx context.Context) error {
	_, err := q.db.Exec(ctx, replaceTrendingScores)
	return err
}

const tasteSet = `-- name: TasteSet :many
SELECT favorites.anime_id FROM favorites WHERE favorites.user_id = $1
UNION
SELECT list_entries.anime_id FROM list_entries
WHERE list_entries.user_id = $1 AND list_entries.score >= 8
`

// A user's taste = favorites plus anything they scored 8+.
func (q *Queries) TasteSet(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, tasteSet, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var anime_id int64
		if err := rows.Scan(&anime_id); err != nil {
			return nil, err
		}
		items = append(items, anime_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upstreamTrendingSignal = `-- name: UpstreamTrendingSignal :many
SELECT id AS anime_id, anilist_trending
FROM anime
WHERE anilist_trending > 0 AND is_adult = FALSE
`

type UpstreamTrendingSignalRow struct {
	AnimeID         int64
	AnilistTrending int32
}

func (q *Queries) UpstreamTrendingSignal(ctx context.Context) ([]UpstreamTrendingSignalRow, error) {
	rows, err := q.db.Query(ctx, upstreamTrendingSignal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpstreamTrendingSignalRow
	for rows.Next() {
		var i UpstreamTrendingSignalRow
		if err := rows.Scan(&i.AnimeID, &i.AnilistTrending); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userListStatusFor = `-- name: UserListStatusFor :many
SELECT anime_id, status FROM list_entries
WHERE user_id = $1 AND anime_id = ANY($2::bigint[])
`

type UserListStatusForParams struct {
	UserID   int64
	AnimeIds []int64
}

type UserListStatusForRow struct {
	AnimeID int64
	Status  ListStatus
}

func (q *Queries) UserListStatusFor(ctx context.Context, arg UserListStatusForParams) ([]UserListStatusForRow, error) {
	rows, err := q.db.Query(ctx, userListStatusFor, arg.UserID, arg.AnimeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserListStatusForRow
	for rows.Next() {
		var i UserListStatusForRow
		if err := rows.Scan(&i.AnimeID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
