// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discussions.sql

package sqlcgen

import (
	"context"
	"time"
)

const addReaction = `-- name: AddReaction :execrows
INSERT INTO comment_reactions (comment_id, user_id, emoji) VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddReactionParams struct {
	CommentID int64
	UserID    int64
	Emoji     string
}

func (q *Queries) AddReaction(ctx context.Context, arg AddReactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, addReaction, arg.CommentID, arg.UserID, arg.Emoji)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bumpThread = `-- name: BumpThread :exec
UPDATE threads SET comment_count = comment_count + 1, last_activity_at = now()
WHERE id = $1
`

func (q *Queries) BumpThread(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, bumpThread, id)
	return err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (thread_id, parent_id, user_id, body, timestamp_seconds, has_spoilers)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, thread_id, parent_id, user_id, body, timestamp_seconds, has_spoilers, deleted_at, created_at, updated_at
`

type CreateCommentParams struct {
	ThreadID         int64
	ParentID         *int64
	UserID           int64
	Body             string
	TimestampSeconds *int32
	HasSpoilers      bool
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.ThreadID,
		arg.ParentID,
		arg.UserID,
		arg.Body,
		arg.TimestampSeconds,
		arg.HasSpoilers,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.ParentID,
		&i.UserID,
		&i.Body,
		&i.TimestampSeconds,
		&i.HasSpoilers,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEpisodeThread = `-- name: CreateEpisodeThread :one
INSERT INTO threads (anime_id, episode_id, kind) VALUES ($1, $2, 'episode')
ON CONFLICT DO NOTHING
RETURNING id, anime_id, episode_id, kind, comment_count, last_activity_at, created_at
`

type CreateEpisodeThreadParams struct {
	AnimeID   int64
	EpisodeID *int64
}

func (q *Queries) CreateEpisodeThread(ctx context.Context, arg CreateEpisodeThreadParams) (Thread, error) {
	row := q.db.QueryRow(ctx, createEpisodeThread, arg.AnimeID, arg.EpisodeID)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.AnimeID,
		&i.EpisodeID,
		&i.Kind,
		&i.CommentCount,
		&i.LastActivityAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSeriesThread = `-- name: CreateSeriesThread :one
INSERT INTO threads (anime_id, kind) VALUES ($1, 'series')
ON CONFLICT DO NOTHING
RETURNING id, anime_id, episode_id, kind, comment_count, last_activity_at, created_at
`

func (q *Queries) CreateSeriesThread(ctx context.Context, animeID int64) (Thread, error) {
	row := q.db.QueryRow(ctx, createSeriesThread, animeID)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.AnimeID,
		&i.EpisodeID,
		&i.Kind,
		&i.CommentCount,
		&i.LastActivityAt,
		&i.CreatedAt,
	)
	return i, err
}

const getComment = `-- name: GetComment :one
SELECT id, thread_id, parent_id, user_id, body, timestamp_seconds, has_spoilers, deleted_at, created_at, updated_at FROM comments WHERE id = $1
`

func (q *Queries) GetComment(ctx context.Context, id int64) (Comment, error) {
	row := q.db.QueryRow(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.ParentID,
		&i.UserID,
		&i.Body,
		&i.TimestampSeconds,
		&i.HasSpoilers,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEpisodeByNumber = `-- name: GetEpisodeByNumber :one
SELECT id, anime_id, number, title, airing_at, created_at FROM episodes WHERE anime_id = $1 AND number = $2
`

type GetEpisodeByNumberParams struct {
	AnimeID int64
	Number  int32
}

func (q *Queries) GetEpisodeByNumber(ctx context.Context, arg GetEpisodeByNumberParams) (Episode, error) {
	row := q.db.QueryRow(ctx, getEpisodeByNumber, arg.AnimeID, arg.Number)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.AnimeID,
		&i.Number,
		&i.Title,
		&i.AiringAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEpisodeThread = `-- name: GetEpisodeThread :one
SELECT id, anime_id, episode_id, kind, comment_count, last_activity_at, created_at FROM threads WHERE episode_id = $1 AND kind = 'episode'
`

func (q *Queries) GetEpisodeThread(ctx context.Context, episodeID *int64) (Thread, error) {
	row := q.db.QueryRow(ctx, getEpisodeThread, episodeID)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.AnimeID,
		&i.EpisodeID,
		&i.Kind,
		&i.CommentCount,
		&i.LastActivityAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSeriesThread = `-- name: GetSeriesThread :one
SELECT id, anime_id, episode_id, kind, comment_count, last_activity_at, created_at FROM threads WHERE anime_id = $1 AND kind = 'series'
`

func (q *Queries) GetSeriesThread(ctx context.Context, animeID int64) (Thread, error) {
	row := q.db.QueryRow(ctx, getSeriesThread, animeID)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.AnimeID,
		&i.EpisodeID,
		&i.Kind,
		&i.CommentCount,
		&i.LastActivityAt,
		&i.CreatedAt,
	)
	return i, err
}

const getThread = `-- name: GetThread :one
SELECT id, anime_id, episode_id, kind, comment_count, last_activity_at, created_at FROM threads WHERE id = $1
`

func (q *Queries) GetThread(ctx context.Context, id int64) (Thread, error) {
	row := q.db.QueryRow(ctx, getThread, id)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.AnimeID,
		&i.EpisodeID,
		&i.Kind,
		&i.CommentCount,
		&i.LastActivityAt,
		&i.CreatedAt,
	)
	return i, err
}

const listComments = `-- name: ListComments :many
SELECT comments.id, comments.thread_id, comments.parent_id, comments.user_id, comments.body, comments.timestamp_seconds, comments.has_spoilers, comments.deleted_at, comments.created_at, comments.updated_at, users.id, users.email, users.username, users.password_hash, users.discord_id, users.avatar_url, users.bio, users.favorite_genres, users.role, users.email_verified_at, users.created_at, users.updated_at
FROM comments
JOIN users ON users.id = comments.user_id
WHERE comments.thread_id = $1
ORDER BY comments.id
LIMIT $2
`

type ListCommentsParams struct {
	ThreadID int64
	Limit    int32
}

type ListCommentsRow struct {
	Comment Comment
	User    User
}

func (q *Queries) ListComments(ctx context.Context, arg ListCommentsParams) ([]ListCommentsRow, error) {
	rows, err := q.db.Query(ctx, listComments, arg.ThreadID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsRow
	for rows.Next() {
		var i ListCommentsRow
		if err := rows.Scan(
			&i.Comment.ID,
			&i.Comment.ThreadID,
			&i.Comment.ParentID,
			&i.Comment.UserID,
			&i.Comment.Body,
			&i.Comment.TimestampSeconds,
			&i.Comment.HasSpoilers,
			&i.Comment.DeletedAt,
			&i.Comment.CreatedAt,
			&i.Comment.UpdatedAt,
			&i.User.ID,
			&i.User.Email,
			&i.User.Username,
			&i.User.PasswordHash,
			&i.User.DiscordID,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.FavoriteGenres,
			&i.User.Role,
			&i.User.EmailVerifiedAt,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodeThreadSummaries = `-- name: ListEpisodeThreadSummaries :many
SELECT episodes.number, threads.id AS thread_id, threads.comment_count, threads.last_activity_at
FROM threads
JOIN episodes ON episodes.id = threads.episode_id
WHERE threads.anime_id = $1 AND threads.kind = 'episode'
ORDER BY episodes.number
`

type ListEpisodeThreadSummariesRow struct {
	Number         int32
	ThreadID       int64
	CommentCount   int32
	LastActivityAt time.Time
}

func (q *Queries) ListEpisodeThreadSummaries(ctx context.Context, animeID int64) ([]ListEpisodeThreadSummariesRow, error) {
	rows, err := q.db.Query(ctx, listEpisodeThreadSummaries, animeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEpisodeThreadSummariesRow
	for rows.Next() {
		var i ListEpisodeThreadSummariesRow
		if err := rows.Scan(
			&i.Number,
			&i.ThreadID,
			&i.CommentCount,
			&i.LastActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactionCountFor = `-- name: ReactionCountFor :one
SELECT COUNT(*)::bigint FROM comment_reactions
WHERE comment_id = $1 AND emoji = $2
`

type ReactionCountForParams struct {
	CommentID int64
	Emoji     string
}

func (q *Queries) ReactionCountFor(ctx context.Context, arg ReactionCountForParams) (int64, error) {
	row := q.db.QueryRow(ctx, reactionCountFor, arg.CommentID, arg.Emoji)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const reactionCounts = `-- name: ReactionCounts :many
SELECT comment_id, emoji, COUNT(*)::bigint AS count
FROM comment_reactions
WHERE comment_id = ANY($1::bigint[])
GROUP BY comment_id, emoji
`

type ReactionCountsRow struct {
	CommentID int64
	Emoji     string
	Count     int64
}

func (q *Queries) ReactionCounts(ctx context.Context, dollar_1 []int64) ([]ReactionCountsRow, error) {
	rows, err := q.db.Query(ctx, reactionCounts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReactionCountsRow
	for rows.Next() {
		var i ReactionCountsRow
		if err := rows.Scan(&i.CommentID, &i.Emoji, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentComments = `-- name: RecentComments :many
SELECT thread_id, created_at FROM comments
WHERE created_at >= $1 AND deleted_at IS NULL
`

type RecentCommentsRow struct {
	ThreadID  int64
	CreatedAt time.Time
}

// Live comments in the velocity window, for thread-trending scoring.
func (q *Queries) RecentComments(ctx context.Context, createdAt time.Time) ([]RecentCommentsRow, error) {
	rows, err := q.db.Query(ctx, recentComments, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentCommentsRow
	for rows.Next() {
		var i RecentCommentsRow
		if err := rows.Scan(&i.ThreadID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeReaction = `-- name: RemoveReaction :execrows
DELETE FROM comment_reactions WHERE comment_id = $1 AND user_id = $2 AND emoji = $3
`

type RemoveReactionParams struct {
	CommentID int64
	UserID    int64
	Emoji     string
}

func (q *Queries) RemoveReaction(ctx context.Context, arg RemoveReactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeReaction, arg.CommentID, arg.UserID, arg.Emoji)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteComment = `-- name: SoftDeleteComment :execrows
UPDATE comments SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteComment(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteComment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const threadsWithContext = `-- name: ThreadsWithContext :many
SELECT threads.id, threads.anime_id, threads.episode_id, threads.kind, threads.comment_count, threads.last_activity_at, threads.created_at, anime.id, anime.anilist_id, anime.title_romaji, anime.title_english, anime.title_native, anime.synonyms, anime.description, anime.format, anime.status, anime.season, anime.season_year, anime.episodes_count, anime.duration_min, anime.genres, anime.tags, anime.studios, anime.cover_image, anime.cover_color, anime.banner_image, anime.average_score, anime.popularity, anime.anilist_trending, anime.is_adult, anime.next_airing_at, anime.next_airing_episode, anime.synced_at, anime.created_at, anime.updated_at, anime.search_doc, anime.mal_id,
       episodes.number AS episode_number,
       episodes.title AS episode_title,
       episodes.airing_at AS episode_airing_at
FROM threads
JOIN anime ON anime.id = threads.anime_id
LEFT JOIN episodes ON episodes.id = threads.episode_id
WHERE threads.id = ANY($1::bigint[])
`

type ThreadsWithContextRow struct {
	Thread          Thread
	Anime           Anime
	EpisodeNumber   *int32
	EpisodeTitle    *string
	EpisodeAiringAt *time.Time
}

// Hydrates ranked thread ids with their anime and (for episode threads) the
// episode row. Order is restored in Go from the ranked id list.
func (q *Queries) ThreadsWithContext(ctx context.Context, threadIds []int64) ([]ThreadsWithContextRow, error) {
	rows, err := q.db.Query(ctx, threadsWithContext, threadIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ThreadsWithContextRow
	for rows.Next() {
		var i ThreadsWithContextRow
		if err := rows.Scan(
			&i.Thread.ID,
			&i.Thread.AnimeID,
			&i.Thread.EpisodeID,
			&i.Thread.Kind,
			&i.Thread.CommentCount,
			&i.Thread.LastActivityAt,
			&i.Thread.CreatedAt,
			&i.Anime.ID,
			&i.Anime.AnilistID,
			&i.Anime.TitleRomaji,
			&i.Anime.TitleEnglish,
			&i.Anime.TitleNative,
			&i.Anime.Synonyms,
			&i.Anime.Description,
			&i.Anime.Format,
			&i.Anime.Status,
			&i.Anime.Season,
			&i.Anime.SeasonYear,
			&i.Anime.EpisodesCount,
			&i.Anime.DurationMin,
			&i.Anime.Genres,
			&i.Anime.Tags,
			&i.Anime.Studios,
			&i.Anime.CoverImage,
			&i.Anime.CoverColor,
			&i.Anime.BannerImage,
			&i.Anime.AverageScore,
			&i.Anime.Popularity,
			&i.Anime.AnilistTrending,
			&i.Anime.IsAdult,
			&i.Anime.NextAiringAt,
			&i.Anime.NextAiringEpisode,
			&i.Anime.SyncedAt,
			&i.Anime.CreatedAt,
			&i.Anime.UpdatedAt,
			&i.Anime.SearchDoc,
			&i.Anime.MalID,
			&i.EpisodeNumber,
			&i.EpisodeTitle,
			&i.EpisodeAiringAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userReactions = `-- name: UserReactions :many
SELECT comment_id, emoji FROM comment_reactions
WHERE user_id = $1 AND comment_id = ANY($2::bigint[])
`

type UserReactionsParams struct {
	UserID  int64
	Column2 []int64
}

type UserReactionsRow struct {
	CommentID int64
	Emoji     string
}

func (q *Queries) UserReactions(ctx context.Context, arg UserReactionsParams) ([]UserReactionsRow, error) {
	rows, err := q.db.Query(ctx, userReactions, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserReactionsRow
	for rows.Next() {
		var i UserReactionsRow
		if err := rows.Scan(&i.CommentID, &i.Emoji); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
