// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: friends.sql

package sqlcgen

import (
	"context"
	"time"
)

const areFriends = `-- name: AreFriends :one
SELECT EXISTS(
  SELECT 1 FROM friendships
  WHERE user_a = LEAST($1::bigint, $2::bigint) AND user_b = GREATEST($1::bigint, $2::bigint)
)
`

type AreFriendsParams struct {
	Column1 int64
	Column2 int64
}

func (q *Queries) AreFriends(ctx context.Context, arg AreFriendsParams) (bool, error) {
	row := q.db.QueryRow(ctx, areFriends, arg.Column1, arg.Column2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createFriendRequest = `-- name: CreateFriendRequest :execrows

INSERT INTO friend_requests (requester_id, addressee_id, note)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type CreateFriendRequestParams struct {
	RequesterID int64
	AddresseeID int64
	Note        string
}

// Friends (docs/PHASE_2.md §M3.9): pending requests, ordered friendships,
// friend-to-friend recommendations, and the people-finding queries.
func (q *Queries) CreateFriendRequest(ctx context.Context, arg CreateFriendRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, createFriendRequest, arg.RequesterID, arg.AddresseeID, arg.Note)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createFriendship = `-- name: CreateFriendship :execrows
INSERT INTO friendships (user_a, user_b)
VALUES (LEAST($1::bigint, $2::bigint), GREATEST($1::bigint, $2::bigint))
ON CONFLICT DO NOTHING
`

type CreateFriendshipParams struct {
	Column1 int64
	Column2 int64
}

func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) (int64, error) {
	result, err := q.db.Exec(ctx, createFriendship, arg.Column1, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFriendRequest = `-- name: DeleteFriendRequest :execrows
DELETE FROM friend_requests WHERE requester_id = $1 AND addressee_id = $2
`

type DeleteFriendRequestParams struct {
	RequesterID int64
	AddresseeID int64
}

func (q *Queries) DeleteFriendRequest(ctx context.Context, arg DeleteFriendRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFriendRequest, arg.RequesterID, arg.AddresseeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFriendship = `-- name: DeleteFriendship :execrows
DELETE FROM friendships
WHERE user_a = LEAST($1::bigint, $2::bigint) AND user_b = GREATEST($1::bigint, $2::bigint)
`

type DeleteFriendshipParams struct {
	Column1 int64
	Column2 int64
}

func (q *Queries) DeleteFriendship(ctx context.Context, arg DeleteFriendshipParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFriendship, arg.Column1, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const friendCount = `-- name: FriendCount :one
SELECT COUNT(*)::bigint FROM friendships WHERE user_a = $1 OR user_b = $1
`

func (q *Queries) FriendCount(ctx context.Context, userA int64) (int64, error) {
	row := q.db.QueryRow(ctx, friendCount, userA)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const friendRequestExists = `-- name: FriendRequestExists :one
SELECT EXISTS(SELECT 1 FROM friend_requests WHERE requester_id = $1 AND addressee_id = $2)
`

type FriendRequestExistsParams struct {
	RequesterID int64
	AddresseeID int64
}

func (q *Queries) FriendRequestExists(ctx context.Context, arg FriendRequestExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, friendRequestExists, arg.RequesterID, arg.AddresseeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const friendsOnAnime = `-- name: FriendsOnAnime :many
SELECT users.username, users.avatar_url,
       list_entries.status, list_entries.progress, list_entries.score
FROM friendships
JOIN users ON users.id = CASE WHEN friendships.user_a = $1 THEN friendships.user_b ELSE friendships.user_a END
JOIN list_entries ON list_entries.user_id = users.id AND list_entries.anime_id = $2
WHERE friendships.user_a = $1 OR friendships.user_b = $1
ORDER BY
  CASE list_entries.status
    WHEN 'watching' THEN 0 WHEN 'completed' THEN 1 WHEN 'paused' THEN 2
    WHEN 'planning' THEN 3 ELSE 4 END,
  list_entries.progress DESC,
  users.username
`

type FriendsOnAnimeParams struct {
	UserA   int64
	AnimeID int64
}

type FriendsOnAnimeRow struct {
	Username  string
	AvatarUrl *string
	Status    ListStatus
	Progress  int32
	Score     *int16
}

// Every friend who has the show on their list: watching first (furthest
// along at the top), then completed, then the rest.
func (q *Queries) FriendsOnAnime(ctx context.Context, arg FriendsOnAnimeParams) ([]FriendsOnAnimeRow, error) {
	rows, err := q.db.Query(ctx, friendsOnAnime, arg.UserA, arg.AnimeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FriendsOnAnimeRow
	for rows.Next() {
		var i FriendsOnAnimeRow
		if err := rows.Scan(
			&i.Username,
			&i.AvatarUrl,
			&i.Status,
			&i.Progress,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByUsernames = `-- name: GetUsersByUsernames :many
SELECT id, username FROM users WHERE lower(username::text) = ANY($1::text[])
`

type GetUsersByUsernamesRow struct {
	ID       int64
	Username string
}

// Mention resolution: usernames are citext, callers pass them lowercased.
func (q *Queries) GetUsersByUsernames(ctx context.Context, dollar_1 []string) ([]GetUsersByUsernamesRow, error) {
	rows, err := q.db.Query(ctx, getUsersByUsernames, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersByUsernamesRow
	for rows.Next() {
		var i GetUsersByUsernamesRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFriendRecommendations = `-- name: ListFriendRecommendations :many
SELECT anime.id, anime.anilist_id, anime.title_romaji, anime.title_english, anime.title_native, anime.synonyms, anime.description, anime.format, anime.status, anime.season, anime.season_year, anime.episodes_count, anime.duration_min, anime.genres, anime.tags, anime.studios, anime.cover_image, anime.cover_color, anime.banner_image, anime.average_score, anime.popularity, anime.anilist_trending, anime.is_adult, anime.next_airing_at, anime.next_airing_episode, anime.synced_at, anime.created_at, anime.updated_at, anime.search_doc, anime.mal_id, users.username, users.avatar_url,
       anime_recommendations.note, anime_recommendations.created_at
FROM anime_recommendations
JOIN anime ON anime.id = anime_recommendations.anime_id
JOIN users ON users.id = anime_recommendations.from_user_id
WHERE anime_recommendations.to_user_id = $1
  AND NOT EXISTS (
    SELECT 1 FROM list_entries le
    WHERE le.user_id = $1 AND le.anime_id = anime_recommendations.anime_id
  )
ORDER BY anime_recommendations.created_at DESC
LIMIT $2
`

type ListFriendRecommendationsParams struct {
	ToUserID int64
	Limit    int32
}

type ListFriendRecommendationsRow struct {
	Anime     Anime
	Username  string
	AvatarUrl *string
	Note      string
	CreatedAt time.Time
}

// The home's "friends think you'd like" row: shows friends sent the viewer
// that aren't on their list yet, newest first.
func (q *Queries) ListFriendRecommendations(ctx context.Context, arg ListFriendRecommendationsParams) ([]ListFriendRecommendationsRow, error) {
	rows, err := q.db.Query(ctx, listFriendRecommendations, arg.ToUserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFriendRecommendationsRow
	for rows.Next() {
		var i ListFriendRecommendationsRow
		if err := rows.Scan(
			&i.Anime.ID,
			&i.Anime.AnilistID,
			&i.Anime.TitleRomaji,
			&i.Anime.TitleEnglish,
			&i.Anime.TitleNative,
			&i.Anime.Synonyms,
			&i.Anime.Description,
			&i.Anime.Format,
			&i.Anime.Status,
			&i.Anime.Season,
			&i.Anime.SeasonYear,
			&i.Anime.EpisodesCount,
			&i.Anime.DurationMin,
			&i.Anime.Genres,
			&i.Anime.Tags,
			&i.Anime.Studios,
			&i.Anime.CoverImage,
			&i.Anime.CoverColor,
			&i.Anime.BannerImage,
			&i.Anime.AverageScore,
			&i.Anime.Popularity,
			&i.Anime.AnilistTrending,
			&i.Anime.IsAdult,
			&i.Anime.NextAiringAt,
			&i.Anime.NextAiringEpisode,
			&i.Anime.SyncedAt,
			&i.Anime.CreatedAt,
			&i.Anime.UpdatedAt,
			&i.Anime.SearchDoc,
			&i.Anime.MalID,
			&i.Username,
			&i.AvatarUrl,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFriends = `-- name: ListFriends :many
SELECT users.id, users.username, users.avatar_url, friendships.created_at AS since
FROM friendships
JOIN users ON users.id = CASE WHEN friendships.user_a = $1 THEN friendships.user_b ELSE friendships.user_a END
WHERE friendships.user_a = $1 OR friendships.user_b = $1
ORDER BY friendships.created_at DESC
LIMIT $2
`

type ListFriendsParams struct {
	UserA int64
	Limit int32
}

type ListFriendsRow struct {
	ID        int64
	Username  string
	AvatarUrl *string
	Since     time.Time
}

// The other side of every friendship row the user is on, newest first.
func (q *Queries) ListFriends(ctx context.Context, arg ListFriendsParams) ([]ListFriendsRow, error) {
	rows, err := q.db.Query(ctx, listFriends, arg.UserA, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFriendsRow
	for rows.Next() {
		var i ListFriendsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.AvatarUrl,
			&i.Since,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomingFriendRequests = `-- name: ListIncomingFriendRequests :many
SELECT users.username, users.avatar_url, friend_requests.note, friend_requests.created_at
FROM friend_requests
JOIN users ON users.id = friend_requests.requester_id
WHERE friend_requests.addressee_id = $1
ORDER BY friend_requests.created_at DESC
LIMIT 100
`

type ListIncomingFriendRequestsRow struct {
	Username  string
	AvatarUrl *string
	Note      string
	CreatedAt time.Time
}

func (q *Queries) ListIncomingFriendRequests(ctx context.Context, addresseeID int64) ([]ListIncomingFriendRequestsRow, error) {
	rows, err := q.db.Query(ctx, listIncomingFriendRequests, addresseeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIncomingFriendRequestsRow
	for rows.Next() {
		var i ListIncomingFriendRequestsRow
		if err := rows.Scan(
			&i.Username,
			&i.AvatarUrl,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutgoingFriendRequests = `-- name: ListOutgoingFriendRequests :many
SELECT users.username, users.avatar_url, friend_requests.note, friend_requests.created_at
FROM friend_requests
JOIN users ON users.id = friend_requests.addressee_id
WHERE friend_requests.requester_id = $1
ORDER BY friend_requests.created_at DESC
LIMIT 100
`

type ListOutgoingFriendRequestsRow struct {
	Username  string
	AvatarUrl *string
	Note      string
	CreatedAt time.Time
}

func (q *Queries) ListOutgoingFriendRequests(ctx context.Context, requesterID int64) ([]ListOutgoingFriendRequestsRow, error) {
	rows, err := q.db.Query(ctx, listOutgoingFriendRequests, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOutgoingFriendRequestsRow
	for rows.Next() {
		var i ListOutgoingFriendRequestsRow
		if err := rows.Scan(
			&i.Username,
			&i.AvatarUrl,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recommendationsForAnime = `-- name: RecommendationsForAnime :many
SELECT users.username, users.avatar_url, anime_recommendations.note, anime_recommendations.created_at
FROM anime_recommendations
JOIN users ON users.id = anime_recommendations.from_user_id
WHERE anime_recommendations.to_user_id = $1 AND anime_recommendations.anime_id = $2
ORDER BY anime_recommendations.created_at DESC
`

type RecommendationsForAnimeParams struct {
	ToUserID int64
	AnimeID  int64
}

type RecommendationsForAnimeRow struct {
	Username  string
	AvatarUrl *string
	Note      string
	CreatedAt time.Time
}

// Who recommended this show to the viewer, and why.
func (q *Queries) RecommendationsForAnime(ctx context.Context, arg RecommendationsForAnimeParams) ([]RecommendationsForAnimeRow, error) {
	rows, err := q.db.Query(ctx, recommendationsForAnime, arg.ToUserID, arg.AnimeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecommendationsForAnimeRow
	for rows.Next() {
		var i RecommendationsForAnimeRow
		if err := rows.Scan(
			&i.Username,
			&i.AvatarUrl,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT users.username, users.avatar_url
FROM users
WHERE users.username::text ILIKE $1::text || '%'
   OR users.username::text % $1::text
ORDER BY (users.username::text ILIKE $1::text || '%') DESC,
         similarity(users.username::text, $1::text) DESC,
         users.username
LIMIT 10
`

type SearchUsersRow struct {
	Username  string
	AvatarUrl *string
}

// Prefix matches first, then trigram neighbours (typo tolerance), for the
// "find people" box.
func (q *Queries) SearchUsers(ctx context.Context, dollar_1 string) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersRow
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(&i.Username, &i.AvatarUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suggestedFriends = `-- name: SuggestedFriends :many
SELECT users.username, users.avatar_url
FROM follows mine
JOIN follows theirs ON theirs.follower_id = mine.followee_id AND theirs.followee_id = mine.follower_id
JOIN users ON users.id = mine.followee_id
WHERE mine.follower_id = $1
  AND NOT EXISTS (
    SELECT 1 FROM friendships f
    WHERE f.user_a = LEAST($1::bigint, users.id) AND f.user_b = GREATEST($1::bigint, users.id)
  )
  AND NOT EXISTS (
    SELECT 1 FROM friend_requests r
    WHERE (r.requester_id = $1 AND r.addressee_id = users.id)
       OR (r.requester_id = users.id AND r.addressee_id = $1)
  )
ORDER BY theirs.created_at DESC
LIMIT 12
`

type SuggestedFriendsRow struct {
	Username  string
	AvatarUrl *string
}

// Mutual follows who aren't friends yet and have no request pending either
// way: the cheapest honest "people you may know".
func (q *Queries) SuggestedFriends(ctx context.Context, followerID int64) ([]SuggestedFriendsRow, error) {
	rows, err := q.db.Query(ctx, suggestedFriends, followerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuggestedFriendsRow
	for rows.Next() {
		var i SuggestedFriendsRow
		if err := rows.Scan(&i.Username, &i.AvatarUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRecommendation = `-- name: UpsertRecommendation :one
INSERT INTO anime_recommendations (from_user_id, to_user_id, anime_id, note)
VALUES ($1, $2, $3, $4)
ON CONFLICT (from_user_id, to_user_id, anime_id) DO UPDATE SET
  note = EXCLUDED.note,
  created_at = now()
RETURNING id, from_user_id, to_user_id, anime_id, note, created_at
`

type UpsertRecommendationParams struct {
	FromUserID int64
	ToUserID   int64
	AnimeID    int64
	Note       string
}

// Re-recommending the same show to the same friend refreshes the note and
// bumps it back to the top instead of adding a second row.
func (q *Queries) UpsertRecommendation(ctx context.Context, arg UpsertRecommendationParams) (AnimeRecommendation, error) {
	row := q.db.QueryRow(ctx, upsertRecommendation,
		arg.FromUserID,
		arg.ToUserID,
		arg.AnimeID,
		arg.Note,
	)
	var i AnimeRecommendation
	err := row.Scan(
		&i.ID,
		&i.FromUserID,
		&i.ToUserID,
		&i.AnimeID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}
