// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: imports.sql

package sqlcgen

import (
	"context"
)

const completeImportJob = `-- name: CompleteImportJob :exec
UPDATE import_jobs SET status = 'done', counts = $2 WHERE id = $1
`

type CompleteImportJobParams struct {
	ID     int64
	Counts []byte
}

func (q *Queries) CompleteImportJob(ctx context.Context, arg CompleteImportJobParams) error {
	_, err := q.db.Exec(ctx, completeImportJob, arg.ID, arg.Counts)
	return err
}

const createImportJob = `-- name: CreateImportJob :one
INSERT INTO import_jobs (user_id, source, payload, rows, counts)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, source, status, payload, rows, counts, error, created_at, updated_at
`

type CreateImportJobParams struct {
	UserID  int64
	Source  ImportSource
	Payload []byte
	Rows    []byte
	Counts  []byte
}

func (q *Queries) CreateImportJob(ctx context.Context, arg CreateImportJobParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, createImportJob,
		arg.UserID,
		arg.Source,
		arg.Payload,
		arg.Rows,
		arg.Counts,
	)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Source,
		&i.Status,
		&i.Payload,
		&i.Rows,
		&i.Counts,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failImportJob = `-- name: FailImportJob :exec
UPDATE import_jobs SET status = 'failed', error = $2 WHERE id = $1
`

type FailImportJobParams struct {
	ID    int64
	Error *string
}

func (q *Queries) FailImportJob(ctx context.Context, arg FailImportJobParams) error {
	_, err := q.db.Exec(ctx, failImportJob, arg.ID, arg.Error)
	return err
}

const finishImportJobProcessing = `-- name: FinishImportJobProcessing :exec
UPDATE import_jobs SET status = 'ready', rows = $2, counts = $3
WHERE id = $1
`

type FinishImportJobProcessingParams struct {
	ID     int64
	Rows   []byte
	Counts []byte
}

func (q *Queries) FinishImportJobProcessing(ctx context.Context, arg FinishImportJobProcessingParams) error {
	_, err := q.db.Exec(ctx, finishImportJobProcessing, arg.ID, arg.Rows, arg.Counts)
	return err
}

const getImportJob = `-- name: GetImportJob :one
SELECT id, user_id, source, status, payload, rows, counts, error, created_at, updated_at FROM import_jobs WHERE id = $1
`

func (q *Queries) GetImportJob(ctx context.Context, id int64) (ImportJob, error) {
	row := q.db.QueryRow(ctx, getImportJob, id)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Source,
		&i.Status,
		&i.Payload,
		&i.Rows,
		&i.Counts,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImportJobForUser = `-- name: GetImportJobForUser :one
SELECT id, user_id, source, status, payload, rows, counts, error, created_at, updated_at FROM import_jobs WHERE id = $1 AND user_id = $2
`

type GetImportJobForUserParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetImportJobForUser(ctx context.Context, arg GetImportJobForUserParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, getImportJobForUser, arg.ID, arg.UserID)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Source,
		&i.Status,
		&i.Payload,
		&i.Rows,
		&i.Counts,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markImportJobCommitting = `-- name: MarkImportJobCommitting :execrows
UPDATE import_jobs SET status = 'committing' WHERE id = $1 AND status = 'ready'
`

// Guard: only a ready job can be committed, and only one commit can claim it.
func (q *Queries) MarkImportJobCommitting(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, markImportJobCommitting, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markImportJobProcessing = `-- name: MarkImportJobProcessing :execrows
UPDATE import_jobs SET status = 'processing'
WHERE id = $1 AND status IN ('pending', 'processing')
`

// Idempotent claim: a re-delivered asynq task may re-claim a job stuck in
// 'processing' (a crashed run); any other status means the job moved on and
// the task should be dropped.
func (q *Queries) MarkImportJobProcessing(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, markImportJobProcessing, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reopenImportJob = `-- name: ReopenImportJob :exec
UPDATE import_jobs SET status = 'ready', error = $2 WHERE id = $1
`

type ReopenImportJobParams struct {
	ID    int64
	Error *string
}

// A failed apply rolled back atomically, so the preview is still valid:
// return the job to 'ready' with the error recorded and let commit retry.
func (q *Queries) ReopenImportJob(ctx context.Context, arg ReopenImportJobParams) error {
	_, err := q.db.Exec(ctx, reopenImportJob, arg.ID, arg.Error)
	return err
}

const supersedeReadyImports = `-- name: SupersedeReadyImports :exec
UPDATE import_jobs SET status = 'superseded'
WHERE user_id = $1 AND status = 'ready'
`

// A new import replaces any preview the user walked away from.
func (q *Queries) SupersedeReadyImports(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, supersedeReadyImports, userID)
	return err
}
