// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lists.sql

package sqlcgen

import (
	"context"
	"time"
)

const addFavorite = `-- name: AddFavorite :execrows
INSERT INTO favorites (user_id, anime_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddFavoriteParams struct {
	UserID  int64
	AnimeID int64
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) (int64, error) {
	result, err := q.db.Exec(ctx, addFavorite, arg.UserID, arg.AnimeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createListEntry = `-- name: CreateListEntry :one
INSERT INTO list_entries (user_id, anime_id, status, score, progress, started_on, finished_on)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, anime_id, status, score, progress, started_on, finished_on, created_at, updated_at
`

type CreateListEntryParams struct {
	UserID     int64
	AnimeID    int64
	Status     ListStatus
	Score      *int16
	Progress   int32
	StartedOn  *time.Time
	FinishedOn *time.Time
}

func (q *Queries) CreateListEntry(ctx context.Context, arg CreateListEntryParams) (ListEntry, error) {
	row := q.db.QueryRow(ctx, createListEntry,
		arg.UserID,
		arg.AnimeID,
		arg.Status,
		arg.Score,
		arg.Progress,
		arg.StartedOn,
		arg.FinishedOn,
	)
	var i ListEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AnimeID,
		&i.Status,
		&i.Score,
		&i.Progress,
		&i.StartedOn,
		&i.FinishedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteListEntry = `-- name: DeleteListEntry :execrows
DELETE FROM list_entries WHERE user_id = $1 AND anime_id = $2
`

type DeleteListEntryParams struct {
	UserID  int64
	AnimeID int64
}

func (q *Queries) DeleteListEntry(ctx context.Context, arg DeleteListEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteListEntry, arg.UserID, arg.AnimeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getListEntry = `-- name: GetListEntry :one
SELECT id, user_id, anime_id, status, score, progress, started_on, finished_on, created_at, updated_at FROM list_entries WHERE user_id = $1 AND anime_id = $2
`

type GetListEntryParams struct {
	UserID  int64
	AnimeID int64
}

func (q *Queries) GetListEntry(ctx context.Context, arg GetListEntryParams) (ListEntry, error) {
	row := q.db.QueryRow(ctx, getListEntry, arg.UserID, arg.AnimeID)
	var i ListEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AnimeID,
		&i.Status,
		&i.Score,
		&i.Progress,
		&i.StartedOn,
		&i.FinishedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertActivity = `-- name: InsertActivity :exec
INSERT INTO activities (user_id, type, anime_id, ref_id, payload)
VALUES ($1, $2, $3, $4, $5)
`

type InsertActivityParams struct {
	UserID  int64
	Type    ActivityType
	AnimeID *int64
	RefID   *int64
	Payload []byte
}

func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) error {
	_, err := q.db.Exec(ctx, insertActivity,
		arg.UserID,
		arg.Type,
		arg.AnimeID,
		arg.RefID,
		arg.Payload,
	)
	return err
}

const isFavorite = `-- name: IsFavorite :one
SELECT EXISTS(SELECT 1 FROM favorites WHERE user_id = $1 AND anime_id = $2)
`

type IsFavoriteParams struct {
	UserID  int64
	AnimeID int64
}

func (q *Queries) IsFavorite(ctx context.Context, arg IsFavoriteParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFavorite, arg.UserID, arg.AnimeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listEntriesForUser = `-- name: ListEntriesForUser :many
SELECT list_entries.id, list_entries.user_id, list_entries.anime_id, list_entries.status, list_entries.score, list_entries.progress, list_entries.started_on, list_entries.finished_on, list_entries.created_at, list_entries.updated_at, anime.id, anime.anilist_id, anime.title_romaji, anime.title_english, anime.title_native, anime.synonyms, anime.description, anime.format, anime.status, anime.season, anime.season_year, anime.episodes_count, anime.duration_min, anime.genres, anime.tags, anime.studios, anime.cover_image, anime.cover_color, anime.banner_image, anime.average_score, anime.popularity, anime.anilist_trending, anime.is_adult, anime.next_airing_at, anime.next_airing_episode, anime.synced_at, anime.created_at, anime.updated_at, anime.search_doc
FROM list_entries
JOIN anime ON anime.id = list_entries.anime_id
WHERE list_entries.user_id = $1
  AND ($3::list_status IS NULL OR list_entries.status = $3)
ORDER BY list_entries.updated_at DESC
LIMIT $2
`

type ListEntriesForUserParams struct {
	UserID int64
	Limit  int32
	Status *ListStatus
}

type ListEntriesForUserRow struct {
	ListEntry ListEntry
	Anime     Anime
}

func (q *Queries) ListEntriesForUser(ctx context.Context, arg ListEntriesForUserParams) ([]ListEntriesForUserRow, error) {
	rows, err := q.db.Query(ctx, listEntriesForUser, arg.UserID, arg.Limit, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesForUserRow
	for rows.Next() {
		var i ListEntriesForUserRow
		if err := rows.Scan(
			&i.ListEntry.ID,
			&i.ListEntry.UserID,
			&i.ListEntry.AnimeID,
			&i.ListEntry.Status,
			&i.ListEntry.Score,
			&i.ListEntry.Progress,
			&i.ListEntry.StartedOn,
			&i.ListEntry.FinishedOn,
			&i.ListEntry.CreatedAt,
			&i.ListEntry.UpdatedAt,
			&i.Anime.ID,
			&i.Anime.AnilistID,
			&i.Anime.TitleRomaji,
			&i.Anime.TitleEnglish,
			&i.Anime.TitleNative,
			&i.Anime.Synonyms,
			&i.Anime.Description,
			&i.Anime.Format,
			&i.Anime.Status,
			&i.Anime.Season,
			&i.Anime.SeasonYear,
			&i.Anime.EpisodesCount,
			&i.Anime.DurationMin,
			&i.Anime.Genres,
			&i.Anime.Tags,
			&i.Anime.Studios,
			&i.Anime.CoverImage,
			&i.Anime.CoverColor,
			&i.Anime.BannerImage,
			&i.Anime.AverageScore,
			&i.Anime.Popularity,
			&i.Anime.AnilistTrending,
			&i.Anime.IsAdult,
			&i.Anime.NextAiringAt,
			&i.Anime.NextAiringEpisode,
			&i.Anime.SyncedAt,
			&i.Anime.CreatedAt,
			&i.Anime.UpdatedAt,
			&i.Anime.SearchDoc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFavorites = `-- name: ListFavorites :many
SELECT anime.id, anime.anilist_id, anime.title_romaji, anime.title_english, anime.title_native, anime.synonyms, anime.description, anime.format, anime.status, anime.season, anime.season_year, anime.episodes_count, anime.duration_min, anime.genres, anime.tags, anime.studios, anime.cover_image, anime.cover_color, anime.banner_image, anime.average_score, anime.popularity, anime.anilist_trending, anime.is_adult, anime.next_airing_at, anime.next_airing_episode, anime.synced_at, anime.created_at, anime.updated_at, anime.search_doc, favorites.created_at AS favorited_at
FROM favorites
JOIN anime ON anime.id = favorites.anime_id
WHERE favorites.user_id = $1
ORDER BY favorites.created_at DESC
LIMIT $2
`

type ListFavoritesParams struct {
	UserID int64
	Limit  int32
}

type ListFavoritesRow struct {
	Anime       Anime
	FavoritedAt time.Time
}

func (q *Queries) ListFavorites(ctx context.Context, arg ListFavoritesParams) ([]ListFavoritesRow, error) {
	rows, err := q.db.Query(ctx, listFavorites, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFavoritesRow
	for rows.Next() {
		var i ListFavoritesRow
		if err := rows.Scan(
			&i.Anime.ID,
			&i.Anime.AnilistID,
			&i.Anime.TitleRomaji,
			&i.Anime.TitleEnglish,
			&i.Anime.TitleNative,
			&i.Anime.Synonyms,
			&i.Anime.Description,
			&i.Anime.Format,
			&i.Anime.Status,
			&i.Anime.Season,
			&i.Anime.SeasonYear,
			&i.Anime.EpisodesCount,
			&i.Anime.DurationMin,
			&i.Anime.Genres,
			&i.Anime.Tags,
			&i.Anime.Studios,
			&i.Anime.CoverImage,
			&i.Anime.CoverColor,
			&i.Anime.BannerImage,
			&i.Anime.AverageScore,
			&i.Anime.Popularity,
			&i.Anime.AnilistTrending,
			&i.Anime.IsAdult,
			&i.Anime.NextAiringAt,
			&i.Anime.NextAiringEpisode,
			&i.Anime.SyncedAt,
			&i.Anime.CreatedAt,
			&i.Anime.UpdatedAt,
			&i.Anime.SearchDoc,
			&i.FavoritedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :execrows
DELETE FROM favorites WHERE user_id = $1 AND anime_id = $2
`

type RemoveFavoriteParams struct {
	UserID  int64
	AnimeID int64
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeFavorite, arg.UserID, arg.AnimeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateListEntry = `-- name: UpdateListEntry :one
UPDATE list_entries SET
  status = $3,
  score = $4,
  progress = $5,
  started_on = $6,
  finished_on = $7
WHERE user_id = $1 AND anime_id = $2
RETURNING id, user_id, anime_id, status, score, progress, started_on, finished_on, created_at, updated_at
`

type UpdateListEntryParams struct {
	UserID     int64
	AnimeID    int64
	Status     ListStatus
	Score      *int16
	Progress   int32
	StartedOn  *time.Time
	FinishedOn *time.Time
}

func (q *Queries) UpdateListEntry(ctx context.Context, arg UpdateListEntryParams) (ListEntry, error) {
	row := q.db.QueryRow(ctx, updateListEntry,
		arg.UserID,
		arg.AnimeID,
		arg.Status,
		arg.Score,
		arg.Progress,
		arg.StartedOn,
		arg.FinishedOn,
	)
	var i ListEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AnimeID,
		&i.Status,
		&i.Score,
		&i.Progress,
		&i.StartedOn,
		&i.FinishedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
