// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlcgen

import (
	"context"
	"time"
)

const countUnreadDMs = `-- name: CountUnreadDMs :one
SELECT COALESCE(SUM(t.unread), 0)::bigint FROM (
  SELECT (SELECT COUNT(*) FROM dm_messages m
           WHERE m.thread_id = dm_threads.id
             AND m.sender_id <> $1::bigint
             AND m.id > CASE WHEN dm_threads.user_a = $1::bigint THEN dm_threads.last_read_a ELSE dm_threads.last_read_b END
         ) AS unread
  FROM dm_threads
  WHERE dm_threads.user_a = $1::bigint OR dm_threads.user_b = $1::bigint
) t
`

func (q *Queries) CountUnreadDMs(ctx context.Context, viewer int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadDMs, viewer)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getDMThread = `-- name: GetDMThread :one
SELECT id, user_a, user_b, last_message_at, last_read_a, last_read_b, created_at FROM dm_threads
WHERE user_a = LEAST($1::bigint, $2::bigint) AND user_b = GREATEST($1::bigint, $2::bigint)
`

type GetDMThreadParams struct {
	Column1 int64
	Column2 int64
}

func (q *Queries) GetDMThread(ctx context.Context, arg GetDMThreadParams) (DmThread, error) {
	row := q.db.QueryRow(ctx, getDMThread, arg.Column1, arg.Column2)
	var i DmThread
	err := row.Scan(
		&i.ID,
		&i.UserA,
		&i.UserB,
		&i.LastMessageAt,
		&i.LastReadA,
		&i.LastReadB,
		&i.CreatedAt,
	)
	return i, err
}

const getOrCreateDMThread = `-- name: GetOrCreateDMThread :one

INSERT INTO dm_threads (user_a, user_b)
VALUES (LEAST($1::bigint, $2::bigint), GREATEST($1::bigint, $2::bigint))
ON CONFLICT (user_a, user_b) DO UPDATE SET user_a = EXCLUDED.user_a
RETURNING id, user_a, user_b, last_message_at, last_read_a, last_read_b, created_at
`

type GetOrCreateDMThreadParams struct {
	Column1 int64
	Column2 int64
}

// Direct messages (docs/PHASE_2.md §M3.9): one thread per pair, each side's
// read pointer on the thread row, keyset pages of messages.
// The no-op DO UPDATE makes ON CONFLICT return the existing row.
func (q *Queries) GetOrCreateDMThread(ctx context.Context, arg GetOrCreateDMThreadParams) (DmThread, error) {
	row := q.db.QueryRow(ctx, getOrCreateDMThread, arg.Column1, arg.Column2)
	var i DmThread
	err := row.Scan(
		&i.ID,
		&i.UserA,
		&i.UserB,
		&i.LastMessageAt,
		&i.LastReadA,
		&i.LastReadB,
		&i.CreatedAt,
	)
	return i, err
}

const insertDMMessage = `-- name: InsertDMMessage :one
INSERT INTO dm_messages (thread_id, sender_id, body)
VALUES ($1, $2, $3)
RETURNING id, thread_id, sender_id, body, created_at
`

type InsertDMMessageParams struct {
	ThreadID int64
	SenderID int64
	Body     string
}

func (q *Queries) InsertDMMessage(ctx context.Context, arg InsertDMMessageParams) (DmMessage, error) {
	row := q.db.QueryRow(ctx, insertDMMessage, arg.ThreadID, arg.SenderID, arg.Body)
	var i DmMessage
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.SenderID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listDMInbox = `-- name: ListDMInbox :many
SELECT dm_threads.id AS thread_id,
       peer.username AS peer_username, peer.avatar_url AS peer_avatar,
       last.body AS last_body, last.sender_id AS last_sender_id, last.created_at AS last_at,
       (SELECT COUNT(*) FROM dm_messages m
         WHERE m.thread_id = dm_threads.id
           AND m.sender_id <> $1::bigint
           AND m.id > CASE WHEN dm_threads.user_a = $1::bigint THEN dm_threads.last_read_a ELSE dm_threads.last_read_b END
       )::bigint AS unread
FROM dm_threads
JOIN users peer ON peer.id = CASE WHEN dm_threads.user_a = $1::bigint THEN dm_threads.user_b ELSE dm_threads.user_a END
JOIN LATERAL (
  SELECT body, sender_id, created_at FROM dm_messages
  WHERE thread_id = dm_threads.id ORDER BY id DESC LIMIT 1
) last ON TRUE
WHERE dm_threads.user_a = $1::bigint OR dm_threads.user_b = $1::bigint
ORDER BY dm_threads.last_message_at DESC
LIMIT 50
`

type ListDMInboxRow struct {
	ThreadID     int64
	PeerUsername string
	PeerAvatar   *string
	LastBody     string
	LastSenderID int64
	LastAt       time.Time
	Unread       int64
}

// Every conversation the viewer is in, newest activity first, with the
// peer, the last message, and how many of the peer's messages are past
// the viewer's read pointer.
func (q *Queries) ListDMInbox(ctx context.Context, viewer int64) ([]ListDMInboxRow, error) {
	rows, err := q.db.Query(ctx, listDMInbox, viewer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDMInboxRow
	for rows.Next() {
		var i ListDMInboxRow
		if err := rows.Scan(
			&i.ThreadID,
			&i.PeerUsername,
			&i.PeerAvatar,
			&i.LastBody,
			&i.LastSenderID,
			&i.LastAt,
			&i.Unread,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDMMessages = `-- name: ListDMMessages :many
SELECT id, thread_id, sender_id, body, created_at FROM dm_messages
WHERE thread_id = $1 AND id < $2
ORDER BY id DESC
LIMIT $3
`

type ListDMMessagesParams struct {
	ThreadID int64
	ID       int64
	Limit    int32
}

func (q *Queries) ListDMMessages(ctx context.Context, arg ListDMMessagesParams) ([]DmMessage, error) {
	rows, err := q.db.Query(ctx, listDMMessages, arg.ThreadID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DmMessage
	for rows.Next() {
		var i DmMessage
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.SenderID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDMThreadRead = `-- name: MarkDMThreadRead :exec
UPDATE dm_threads SET
  last_read_a = CASE WHEN user_a = $1::bigint
    THEN GREATEST(last_read_a, (SELECT COALESCE(MAX(m.id), 0) FROM dm_messages m WHERE m.thread_id = $2))
    ELSE last_read_a END,
  last_read_b = CASE WHEN user_b = $1::bigint
    THEN GREATEST(last_read_b, (SELECT COALESCE(MAX(m.id), 0) FROM dm_messages m WHERE m.thread_id = $2))
    ELSE last_read_b END
WHERE id = $2
`

type MarkDMThreadReadParams struct {
	Viewer int64
	Thread int64
}

func (q *Queries) MarkDMThreadRead(ctx context.Context, arg MarkDMThreadReadParams) error {
	_, err := q.db.Exec(ctx, markDMThreadRead, arg.Viewer, arg.Thread)
	return err
}

const touchDMThread = `-- name: TouchDMThread :exec
UPDATE dm_threads SET
  last_message_at = now(),
  last_read_a = CASE WHEN user_a = $1::bigint THEN GREATEST(last_read_a, $2::bigint) ELSE last_read_a END,
  last_read_b = CASE WHEN user_b = $1::bigint THEN GREATEST(last_read_b, $2::bigint) ELSE last_read_b END
WHERE id = $3
`

type TouchDMThreadParams struct {
	Sender  int64
	Message int64
	Thread  int64
}

// After a send: bump recency and move the sender's own pointer past their
// message so their inbox never shows their own words as unread.
func (q *Queries) TouchDMThread(ctx context.Context, arg TouchDMThreadParams) error {
	_, err := q.db.Exec(ctx, touchDMThread, arg.Sender, arg.Message, arg.Thread)
	return err
}
