// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type ActivityType string

const (
	ActivityTypeListAdd      ActivityType = "list_add"
	ActivityTypeStatusChange ActivityType = "status_change"
	ActivityTypeProgress     ActivityType = "progress"
	ActivityTypeCompleted    ActivityType = "completed"
	ActivityTypeScored       ActivityType = "scored"
	ActivityTypeFavorite     ActivityType = "favorite"
	ActivityTypeReview       ActivityType = "review"
	ActivityTypeComment      ActivityType = "comment"
	ActivityTypeHelpfulVote  ActivityType = "helpful_vote"
)

func (e *ActivityType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActivityType(s)
	case string:
		*e = ActivityType(s)
	default:
		return fmt.Errorf("unsupported scan type for ActivityType: %T", src)
	}
	return nil
}

type NullActivityType struct {
	ActivityType ActivityType
	Valid        bool // Valid is true if ActivityType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActivityType) Scan(value interface{}) error {
	if value == nil {
		ns.ActivityType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActivityType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActivityType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActivityType), nil
}

type AnimeFormat string

const (
	AnimeFormatTV      AnimeFormat = "TV"
	AnimeFormatTVSHORT AnimeFormat = "TV_SHORT"
	AnimeFormatMOVIE   AnimeFormat = "MOVIE"
	AnimeFormatSPECIAL AnimeFormat = "SPECIAL"
	AnimeFormatOVA     AnimeFormat = "OVA"
	AnimeFormatONA     AnimeFormat = "ONA"
	AnimeFormatMUSIC   AnimeFormat = "MUSIC"
)

func (e *AnimeFormat) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AnimeFormat(s)
	case string:
		*e = AnimeFormat(s)
	default:
		return fmt.Errorf("unsupported scan type for AnimeFormat: %T", src)
	}
	return nil
}

type NullAnimeFormat struct {
	AnimeFormat AnimeFormat
	Valid       bool // Valid is true if AnimeFormat is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAnimeFormat) Scan(value interface{}) error {
	if value == nil {
		ns.AnimeFormat, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AnimeFormat.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAnimeFormat) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AnimeFormat), nil
}

type AnimeSeason string

const (
	AnimeSeasonWINTER AnimeSeason = "WINTER"
	AnimeSeasonSPRING AnimeSeason = "SPRING"
	AnimeSeasonSUMMER AnimeSeason = "SUMMER"
	AnimeSeasonFALL   AnimeSeason = "FALL"
)

func (e *AnimeSeason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AnimeSeason(s)
	case string:
		*e = AnimeSeason(s)
	default:
		return fmt.Errorf("unsupported scan type for AnimeSeason: %T", src)
	}
	return nil
}

type NullAnimeSeason struct {
	AnimeSeason AnimeSeason
	Valid       bool // Valid is true if AnimeSeason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAnimeSeason) Scan(value interface{}) error {
	if value == nil {
		ns.AnimeSeason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AnimeSeason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAnimeSeason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AnimeSeason), nil
}

type AnimeStatus string

const (
	AnimeStatusFINISHED       AnimeStatus = "FINISHED"
	AnimeStatusRELEASING      AnimeStatus = "RELEASING"
	AnimeStatusNOTYETRELEASED AnimeStatus = "NOT_YET_RELEASED"
	AnimeStatusCANCELLED      AnimeStatus = "CANCELLED"
	AnimeStatusHIATUS         AnimeStatus = "HIATUS"
)

func (e *AnimeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AnimeStatus(s)
	case string:
		*e = AnimeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AnimeStatus: %T", src)
	}
	return nil
}

type NullAnimeStatus struct {
	AnimeStatus AnimeStatus
	Valid       bool // Valid is true if AnimeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAnimeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AnimeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AnimeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAnimeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AnimeStatus), nil
}

type EmailTokenPurpose string

const (
	EmailTokenPurposeVerifyEmail   EmailTokenPurpose = "verify_email"
	EmailTokenPurposeResetPassword EmailTokenPurpose = "reset_password"
)

func (e *EmailTokenPurpose) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EmailTokenPurpose(s)
	case string:
		*e = EmailTokenPurpose(s)
	default:
		return fmt.Errorf("unsupported scan type for EmailTokenPurpose: %T", src)
	}
	return nil
}

type NullEmailTokenPurpose struct {
	EmailTokenPurpose EmailTokenPurpose
	Valid             bool // Valid is true if EmailTokenPurpose is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEmailTokenPurpose) Scan(value interface{}) error {
	if value == nil {
		ns.EmailTokenPurpose, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EmailTokenPurpose.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEmailTokenPurpose) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EmailTokenPurpose), nil
}

type ListStatus string

const (
	ListStatusWatching  ListStatus = "watching"
	ListStatusCompleted ListStatus = "completed"
	ListStatusPlanning  ListStatus = "planning"
	ListStatusPaused    ListStatus = "paused"
	ListStatusDropped   ListStatus = "dropped"
)

func (e *ListStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ListStatus(s)
	case string:
		*e = ListStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ListStatus: %T", src)
	}
	return nil
}

type NullListStatus struct {
	ListStatus ListStatus
	Valid      bool // Valid is true if ListStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullListStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ListStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ListStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullListStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ListStatus), nil
}

type NotificationType string

const (
	NotificationTypeCommentReply NotificationType = "comment_reply"
	NotificationTypeNewFollower  NotificationType = "new_follower"
	NotificationTypeEpisodeAired NotificationType = "episode_aired"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType
	Valid            bool // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type ThreadKind string

const (
	ThreadKindSeries  ThreadKind = "series"
	ThreadKindEpisode ThreadKind = "episode"
)

func (e *ThreadKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ThreadKind(s)
	case string:
		*e = ThreadKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ThreadKind: %T", src)
	}
	return nil
}

type NullThreadKind struct {
	ThreadKind ThreadKind
	Valid      bool // Valid is true if ThreadKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullThreadKind) Scan(value interface{}) error {
	if value == nil {
		ns.ThreadKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ThreadKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullThreadKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ThreadKind), nil
}

type UserRole string

const (
	UserRoleUser  UserRole = "user"
	UserRoleMod   UserRole = "mod"
	UserRoleAdmin UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Activity struct {
	ID        int64
	UserID    int64
	Type      ActivityType
	AnimeID   *int64
	RefID     *int64
	Payload   []byte
	CreatedAt time.Time
}

type Anime struct {
	ID                int64
	AnilistID         int32
	TitleRomaji       string
	TitleEnglish      *string
	TitleNative       *string
	Synonyms          []string
	Description       *string
	Format            *AnimeFormat
	Status            AnimeStatus
	Season            *AnimeSeason
	SeasonYear        *int32
	EpisodesCount     *int32
	DurationMin       *int32
	Genres            []string
	Tags              []byte
	Studios           []byte
	CoverImage        *string
	CoverColor        *string
	BannerImage       *string
	AverageScore      *int32
	Popularity        int32
	AnilistTrending   int32
	IsAdult           bool
	NextAiringAt      *time.Time
	NextAiringEpisode *int32
	SyncedAt          time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
	SearchDoc         interface{}
}

type Comment struct {
	ID               int64
	ThreadID         int64
	ParentID         *int64
	UserID           int64
	Body             string
	TimestampSeconds *int32
	HasSpoilers      bool
	DeletedAt        *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type CommentReaction struct {
	CommentID int64
	UserID    int64
	Emoji     string
	CreatedAt time.Time
}

type EmailToken struct {
	ID        int64
	UserID    int64
	Purpose   EmailTokenPurpose
	TokenHash []byte
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type Episode struct {
	ID        int64
	AnimeID   int64
	Number    int32
	Title     *string
	AiringAt  *time.Time
	CreatedAt time.Time
}

type Favorite struct {
	UserID    int64
	AnimeID   int64
	CreatedAt time.Time
}

type Follow struct {
	FollowerID int64
	FolloweeID int64
	CreatedAt  time.Time
}

type ListEntry struct {
	ID         int64
	UserID     int64
	AnimeID    int64
	Status     ListStatus
	Score      *int16
	Progress   int32
	StartedOn  *time.Time
	FinishedOn *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Notification struct {
	ID        int64
	UserID    int64
	Type      NotificationType
	ActorID   *int64
	AnimeID   *int64
	RefID     *int64
	Payload   []byte
	ReadAt    *time.Time
	CreatedAt time.Time
}

type RefreshToken struct {
	ID        int64
	UserID    int64
	FamilyID  uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	UsedAt    *time.Time
	RevokedAt *time.Time
	CreatedAt time.Time
}

type Review struct {
	ID           int64
	UserID       int64
	AnimeID      int64
	Body         string
	Score        int16
	HasSpoilers  bool
	HelpfulCount int32
	DeletedAt    *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type ReviewVote struct {
	ReviewID  int64
	UserID    int64
	CreatedAt time.Time
}

type Thread struct {
	ID             int64
	AnimeID        int64
	EpisodeID      *int64
	Kind           ThreadKind
	CommentCount   int32
	LastActivityAt time.Time
	CreatedAt      time.Time
}

type TrendingScore struct {
	AnimeID    int64
	Score      float64
	Rank       int32
	ComputedAt time.Time
}

type User struct {
	ID              int64
	Email           string
	Username        string
	PasswordHash    *string
	DiscordID       *string
	AvatarUrl       *string
	Bio             string
	FavoriteGenres  []string
	Role            UserRole
	EmailVerifiedAt *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
