// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moderation.sql

package sqlcgen

import (
	"context"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (reporter_id, subject_type, subject_id, reason)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
RETURNING id
`

type CreateReportParams struct {
	ReporterID  int64
	SubjectType ReportSubject
	SubjectID   int64
	Reason      string
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (int64, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ReporterID,
		arg.SubjectType,
		arg.SubjectID,
		arg.Reason,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listOpenReports = `-- name: ListOpenReports :many
SELECT reports.id, reports.reporter_id, reports.subject_type, reports.subject_id, reports.reason, reports.status, reports.resolved_by, reports.resolved_at, reports.created_at, users.username AS reporter_username
FROM reports
JOIN users ON users.id = reports.reporter_id
WHERE reports.status = 'open' AND reports.id < $1
ORDER BY reports.id DESC
LIMIT $2
`

type ListOpenReportsParams struct {
	ID    int64
	Limit int32
}

type ListOpenReportsRow struct {
	Report           Report
	ReporterUsername string
}

func (q *Queries) ListOpenReports(ctx context.Context, arg ListOpenReportsParams) ([]ListOpenReportsRow, error) {
	rows, err := q.db.Query(ctx, listOpenReports, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenReportsRow
	for rows.Next() {
		var i ListOpenReportsRow
		if err := rows.Scan(
			&i.Report.ID,
			&i.Report.ReporterID,
			&i.Report.SubjectType,
			&i.Report.SubjectID,
			&i.Report.Reason,
			&i.Report.Status,
			&i.Report.ResolvedBy,
			&i.Report.ResolvedAt,
			&i.Report.CreatedAt,
			&i.ReporterUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveReport = `-- name: ResolveReport :execrows
UPDATE reports SET status = $2, resolved_by = $3, resolved_at = now()
WHERE id = $1 AND status = 'open'
`

type ResolveReportParams struct {
	ID         int64
	Status     ReportStatus
	ResolvedBy *int64
}

func (q *Queries) ResolveReport(ctx context.Context, arg ResolveReportParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveReport, arg.ID, arg.Status, arg.ResolvedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
