// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlcgen

import (
	"context"
	"time"
)

const airedEpisodesBetween = `-- name: AiredEpisodesBetween :many
SELECT episodes.id, episodes.anime_id, episodes.number, episodes.title, episodes.airing_at, episodes.created_at, anime.id, anime.anilist_id, anime.title_romaji, anime.title_english, anime.title_native, anime.synonyms, anime.description, anime.format, anime.status, anime.season, anime.season_year, anime.episodes_count, anime.duration_min, anime.genres, anime.tags, anime.studios, anime.cover_image, anime.cover_color, anime.banner_image, anime.average_score, anime.popularity, anime.anilist_trending, anime.is_adult, anime.next_airing_at, anime.next_airing_episode, anime.synced_at, anime.created_at, anime.updated_at, anime.search_doc
FROM episodes
JOIN anime ON anime.id = episodes.anime_id
WHERE episodes.airing_at > $1 AND episodes.airing_at <= $2
`

type AiredEpisodesBetweenParams struct {
	AiringAt   *time.Time
	AiringAt_2 *time.Time
}

type AiredEpisodesBetweenRow struct {
	Episode Episode
	Anime   Anime
}

func (q *Queries) AiredEpisodesBetween(ctx context.Context, arg AiredEpisodesBetweenParams) ([]AiredEpisodesBetweenRow, error) {
	rows, err := q.db.Query(ctx, airedEpisodesBetween, arg.AiringAt, arg.AiringAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiredEpisodesBetweenRow
	for rows.Next() {
		var i AiredEpisodesBetweenRow
		if err := rows.Scan(
			&i.Episode.ID,
			&i.Episode.AnimeID,
			&i.Episode.Number,
			&i.Episode.Title,
			&i.Episode.AiringAt,
			&i.Episode.CreatedAt,
			&i.Anime.ID,
			&i.Anime.AnilistID,
			&i.Anime.TitleRomaji,
			&i.Anime.TitleEnglish,
			&i.Anime.TitleNative,
			&i.Anime.Synonyms,
			&i.Anime.Description,
			&i.Anime.Format,
			&i.Anime.Status,
			&i.Anime.Season,
			&i.Anime.SeasonYear,
			&i.Anime.EpisodesCount,
			&i.Anime.DurationMin,
			&i.Anime.Genres,
			&i.Anime.Tags,
			&i.Anime.Studios,
			&i.Anime.CoverImage,
			&i.Anime.CoverColor,
			&i.Anime.BannerImage,
			&i.Anime.AverageScore,
			&i.Anime.Popularity,
			&i.Anime.AnilistTrending,
			&i.Anime.IsAdult,
			&i.Anime.NextAiringAt,
			&i.Anime.NextAiringEpisode,
			&i.Anime.SyncedAt,
			&i.Anime.CreatedAt,
			&i.Anime.UpdatedAt,
			&i.Anime.SearchDoc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*)::bigint FROM notifications
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const insertNotification = `-- name: InsertNotification :exec
INSERT INTO notifications (user_id, type, actor_id, anime_id, ref_id, payload)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertNotificationParams struct {
	UserID  int64
	Type    NotificationType
	ActorID *int64
	AnimeID *int64
	RefID   *int64
	Payload []byte
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.Exec(ctx, insertNotification,
		arg.UserID,
		arg.Type,
		arg.ActorID,
		arg.AnimeID,
		arg.RefID,
		arg.Payload,
	)
	return err
}

const listNotifications = `-- name: ListNotifications :many
SELECT notifications.id, notifications.user_id, notifications.type, notifications.actor_id, notifications.anime_id, notifications.ref_id, notifications.payload, notifications.read_at, notifications.created_at, actor.username AS actor_username, actor.avatar_url AS actor_avatar
FROM notifications
LEFT JOIN users actor ON actor.id = notifications.actor_id
WHERE notifications.user_id = $1 AND notifications.id < $2
ORDER BY notifications.id DESC
LIMIT $3
`

type ListNotificationsParams struct {
	UserID int64
	ID     int64
	Limit  int32
}

type ListNotificationsRow struct {
	Notification  Notification
	ActorUsername *string
	ActorAvatar   *string
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.UserID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationsRow
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.Notification.ID,
			&i.Notification.UserID,
			&i.Notification.Type,
			&i.Notification.ActorID,
			&i.Notification.AnimeID,
			&i.Notification.RefID,
			&i.Notification.Payload,
			&i.Notification.ReadAt,
			&i.Notification.CreatedAt,
			&i.ActorUsername,
			&i.ActorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET read_at = now()
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationsRead = `-- name: MarkNotificationsRead :exec
UPDATE notifications SET read_at = now()
WHERE user_id = $1 AND id = ANY($2::bigint[]) AND read_at IS NULL
`

type MarkNotificationsReadParams struct {
	UserID  int64
	Column2 []int64
}

func (q *Queries) MarkNotificationsRead(ctx context.Context, arg MarkNotificationsReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationsRead, arg.UserID, arg.Column2)
	return err
}

const watcherIDs = `-- name: WatcherIDs :many
SELECT user_id FROM list_entries
WHERE anime_id = $1 AND status = 'watching'
`

func (q *Queries) WatcherIDs(ctx context.Context, animeID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, watcherIDs, animeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
