// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pulse.sql

package sqlcgen

import (
	"context"
	"time"
)

const repliesToUser = `-- name: RepliesToUser :many
SELECT c.id, c.body, c.created_at,
       actor.username AS actor_username,
       actor.avatar_url AS actor_avatar,
       anime.id, anime.anilist_id, anime.title_romaji, anime.title_english, anime.title_native, anime.synonyms, anime.description, anime.format, anime.status, anime.season, anime.season_year, anime.episodes_count, anime.duration_min, anime.genres, anime.tags, anime.studios, anime.cover_image, anime.cover_color, anime.banner_image, anime.average_score, anime.popularity, anime.anilist_trending, anime.is_adult, anime.next_airing_at, anime.next_airing_episode, anime.synced_at, anime.created_at, anime.updated_at, anime.search_doc, anime.mal_id,
       episodes.number AS episode_number,
       threads.kind AS thread_kind,
       parent.body AS parent_body
FROM comments c
JOIN comments parent ON parent.id = c.parent_id
JOIN users actor ON actor.id = c.user_id
JOIN threads ON threads.id = c.thread_id
JOIN anime ON anime.id = threads.anime_id
LEFT JOIN episodes ON episodes.id = threads.episode_id
WHERE parent.user_id = $1
  AND c.user_id <> $1
  AND c.deleted_at IS NULL
ORDER BY c.created_at DESC
LIMIT $2
`

type RepliesToUserParams struct {
	UserID int64
	Lim    int32
}

type RepliesToUserRow struct {
	ID            int64
	Body          string
	CreatedAt     time.Time
	ActorUsername string
	ActorAvatar   *string
	Anime         Anime
	EpisodeNumber *int32
	ThreadKind    ThreadKind
	ParentBody    string
}

// Replies other people left on the viewer's comments, newest first.
func (q *Queries) RepliesToUser(ctx context.Context, arg RepliesToUserParams) ([]RepliesToUserRow, error) {
	rows, err := q.db.Query(ctx, repliesToUser, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepliesToUserRow
	for rows.Next() {
		var i RepliesToUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.CreatedAt,
			&i.ActorUsername,
			&i.ActorAvatar,
			&i.Anime.ID,
			&i.Anime.AnilistID,
			&i.Anime.TitleRomaji,
			&i.Anime.TitleEnglish,
			&i.Anime.TitleNative,
			&i.Anime.Synonyms,
			&i.Anime.Description,
			&i.Anime.Format,
			&i.Anime.Status,
			&i.Anime.Season,
			&i.Anime.SeasonYear,
			&i.Anime.EpisodesCount,
			&i.Anime.DurationMin,
			&i.Anime.Genres,
			&i.Anime.Tags,
			&i.Anime.Studios,
			&i.Anime.CoverImage,
			&i.Anime.CoverColor,
			&i.Anime.BannerImage,
			&i.Anime.AverageScore,
			&i.Anime.Popularity,
			&i.Anime.AnilistTrending,
			&i.Anime.IsAdult,
			&i.Anime.NextAiringAt,
			&i.Anime.NextAiringEpisode,
			&i.Anime.SyncedAt,
			&i.Anime.CreatedAt,
			&i.Anime.UpdatedAt,
			&i.Anime.SearchDoc,
			&i.Anime.MalID,
			&i.EpisodeNumber,
			&i.ThreadKind,
			&i.ParentBody,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userActiveDays = `-- name: UserActiveDays :many

SELECT DISTINCT (activities.created_at AT TIME ZONE $1::text)::date AS day
FROM activities
WHERE activities.user_id = $2
  AND activities.created_at > now() - interval '400 days'
ORDER BY day DESC
`

type UserActiveDaysParams struct {
	Tz     string
	UserID int64
}

// The viewer's pulse (§M3.8): the raw material for streaks, badges, replies
// and kudos. Everything is scoped to one user and bounded, so the home can
// ask on every visit.
// Distinct calendar days (in the viewer's zone) with any activity — the
// streak's raw material. Bounded to ~a year: a streak longer than that is a
// life, not a statistic.
func (q *Queries) UserActiveDays(ctx context.Context, arg UserActiveDaysParams) ([]time.Time, error) {
	rows, err := q.db.Query(ctx, userActiveDays, arg.Tz, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []time.Time
	for rows.Next() {
		var day time.Time
		if err := rows.Scan(&day); err != nil {
			return nil, err
		}
		items = append(items, day)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userBadgeCounts = `-- name: UserBadgeCounts :one
SELECT
  (SELECT COUNT(*) FROM comments c
     WHERE c.user_id = $1 AND c.deleted_at IS NULL)::bigint AS comments,
  (SELECT COUNT(DISTINCT t.anime_id) FROM comments c
     JOIN threads t ON t.id = c.thread_id
     WHERE c.user_id = $1 AND c.deleted_at IS NULL)::bigint AS shows_discussed,
  (SELECT COUNT(*) FROM list_entries le
     WHERE le.user_id = $1 AND le.status = 'completed')::bigint AS completed,
  (SELECT COUNT(*) FROM favorites f WHERE f.user_id = $1)::bigint AS favorites,
  (SELECT COUNT(*) FROM reviews r WHERE r.user_id = $1)::bigint AS reviews,
  (SELECT COUNT(*) FROM comments c
     WHERE c.user_id = $1 AND c.deleted_at IS NULL
       AND EXTRACT(HOUR FROM c.created_at AT TIME ZONE $2::text) < 4)::bigint AS night_comments,
  (SELECT COUNT(*) FROM comments c
     JOIN threads t ON t.id = c.thread_id
     JOIN episodes e ON e.id = t.episode_id
     WHERE c.user_id = $1 AND c.deleted_at IS NULL
       AND e.airing_at IS NOT NULL
       AND c.created_at BETWEEN e.airing_at AND e.airing_at + interval '1 hour')::bigint AS early_comments,
  (SELECT COUNT(*) FROM comment_reactions cr
     JOIN comments c ON c.id = cr.comment_id
     WHERE c.user_id = $1 AND cr.user_id <> $1)::bigint AS reactions_received,
  (SELECT COUNT(*) FROM comment_reactions cr
     JOIN comments c ON c.id = cr.comment_id
     WHERE c.user_id = $1 AND cr.user_id <> $1
       AND cr.created_at > now() - interval '7 days')::bigint AS reactions_week
`

type UserBadgeCountsParams struct {
	UserID int64
	Tz     string
}

type UserBadgeCountsRow struct {
	Comments          int64
	ShowsDiscussed    int64
	Completed         int64
	Favorites         int64
	Reviews           int64
	NightComments     int64
	EarlyComments     int64
	ReactionsReceived int64
	ReactionsWeek     int64
}

// Every badge is a threshold on one of these counters.
func (q *Queries) UserBadgeCounts(ctx context.Context, arg UserBadgeCountsParams) (UserBadgeCountsRow, error) {
	row := q.db.QueryRow(ctx, userBadgeCounts, arg.UserID, arg.Tz)
	var i UserBadgeCountsRow
	err := row.Scan(
		&i.Comments,
		&i.ShowsDiscussed,
		&i.Completed,
		&i.Favorites,
		&i.Reviews,
		&i.NightComments,
		&i.EarlyComments,
		&i.ReactionsReceived,
		&i.ReactionsWeek,
	)
	return i, err
}

const userTopReactedComments = `-- name: UserTopReactedComments :many
SELECT c.id, c.body,
       anime.id, anime.anilist_id, anime.title_romaji, anime.title_english, anime.title_native, anime.synonyms, anime.description, anime.format, anime.status, anime.season, anime.season_year, anime.episodes_count, anime.duration_min, anime.genres, anime.tags, anime.studios, anime.cover_image, anime.cover_color, anime.banner_image, anime.average_score, anime.popularity, anime.anilist_trending, anime.is_adult, anime.next_airing_at, anime.next_airing_episode, anime.synced_at, anime.created_at, anime.updated_at, anime.search_doc, anime.mal_id,
       episodes.number AS episode_number,
       threads.kind AS thread_kind,
       COUNT(*)::bigint AS reactions
FROM comments c
JOIN comment_reactions cr ON cr.comment_id = c.id AND cr.user_id <> c.user_id
JOIN threads ON threads.id = c.thread_id
JOIN anime ON anime.id = threads.anime_id
LEFT JOIN episodes ON episodes.id = threads.episode_id
WHERE c.user_id = $1
  AND c.deleted_at IS NULL
  AND cr.created_at > now() - interval '7 days'
GROUP BY c.id, anime.id, episodes.number, threads.kind
ORDER BY reactions DESC, c.created_at DESC
LIMIT 3
`

type UserTopReactedCommentsRow struct {
	ID            int64
	Body          string
	Anime         Anime
	EpisodeNumber *int32
	ThreadKind    ThreadKind
	Reactions     int64
}

// The viewer's comments that drew reactions this week, most-reacted first.
func (q *Queries) UserTopReactedComments(ctx context.Context, userID int64) ([]UserTopReactedCommentsRow, error) {
	rows, err := q.db.Query(ctx, userTopReactedComments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserTopReactedCommentsRow
	for rows.Next() {
		var i UserTopReactedCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.Anime.ID,
			&i.Anime.AnilistID,
			&i.Anime.TitleRomaji,
			&i.Anime.TitleEnglish,
			&i.Anime.TitleNative,
			&i.Anime.Synonyms,
			&i.Anime.Description,
			&i.Anime.Format,
			&i.Anime.Status,
			&i.Anime.Season,
			&i.Anime.SeasonYear,
			&i.Anime.EpisodesCount,
			&i.Anime.DurationMin,
			&i.Anime.Genres,
			&i.Anime.Tags,
			&i.Anime.Studios,
			&i.Anime.CoverImage,
			&i.Anime.CoverColor,
			&i.Anime.BannerImage,
			&i.Anime.AverageScore,
			&i.Anime.Popularity,
			&i.Anime.AnilistTrending,
			&i.Anime.IsAdult,
			&i.Anime.NextAiringAt,
			&i.Anime.NextAiringEpisode,
			&i.Anime.SyncedAt,
			&i.Anime.CreatedAt,
			&i.Anime.UpdatedAt,
			&i.Anime.SearchDoc,
			&i.Anime.MalID,
			&i.EpisodeNumber,
			&i.ThreadKind,
			&i.Reactions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
