// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package sqlcgen

import (
	"context"
)

const addReviewVote = `-- name: AddReviewVote :execrows
INSERT INTO review_votes (review_id, user_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddReviewVoteParams struct {
	ReviewID int64
	UserID   int64
}

func (q *Queries) AddReviewVote(ctx context.Context, arg AddReviewVoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, addReviewVote, arg.ReviewID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adjustHelpfulCount = `-- name: AdjustHelpfulCount :one
UPDATE reviews SET helpful_count = helpful_count + $2
WHERE id = $1
RETURNING helpful_count
`

type AdjustHelpfulCountParams struct {
	ID           int64
	HelpfulCount int32
}

func (q *Queries) AdjustHelpfulCount(ctx context.Context, arg AdjustHelpfulCountParams) (int32, error) {
	row := q.db.QueryRow(ctx, adjustHelpfulCount, arg.ID, arg.HelpfulCount)
	var helpful_count int32
	err := row.Scan(&helpful_count)
	return helpful_count, err
}

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (user_id, anime_id, body, score, has_spoilers)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, anime_id, body, score, has_spoilers, helpful_count, deleted_at, created_at, updated_at
`

type CreateReviewParams struct {
	UserID      int64
	AnimeID     int64
	Body        string
	Score       int16
	HasSpoilers bool
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.UserID,
		arg.AnimeID,
		arg.Body,
		arg.Score,
		arg.HasSpoilers,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AnimeID,
		&i.Body,
		&i.Score,
		&i.HasSpoilers,
		&i.HelpfulCount,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReview = `-- name: GetReview :one
SELECT reviews.id, reviews.user_id, reviews.anime_id, reviews.body, reviews.score, reviews.has_spoilers, reviews.helpful_count, reviews.deleted_at, reviews.created_at, reviews.updated_at, users.id, users.email, users.username, users.password_hash, users.discord_id, users.avatar_url, users.bio, users.favorite_genres, users.role, users.email_verified_at, users.created_at, users.updated_at, anime.id, anime.anilist_id, anime.title_romaji, anime.title_english, anime.title_native, anime.synonyms, anime.description, anime.format, anime.status, anime.season, anime.season_year, anime.episodes_count, anime.duration_min, anime.genres, anime.tags, anime.studios, anime.cover_image, anime.cover_color, anime.banner_image, anime.average_score, anime.popularity, anime.anilist_trending, anime.is_adult, anime.next_airing_at, anime.next_airing_episode, anime.synced_at, anime.created_at, anime.updated_at, anime.search_doc, anime.mal_id
FROM reviews
JOIN users ON users.id = reviews.user_id
JOIN anime ON anime.id = reviews.anime_id
WHERE reviews.id = $1 AND reviews.deleted_at IS NULL
`

type GetReviewRow struct {
	Review Review
	User   User
	Anime  Anime
}

func (q *Queries) GetReview(ctx context.Context, id int64) (GetReviewRow, error) {
	row := q.db.QueryRow(ctx, getReview, id)
	var i GetReviewRow
	err := row.Scan(
		&i.Review.ID,
		&i.Review.UserID,
		&i.Review.AnimeID,
		&i.Review.Body,
		&i.Review.Score,
		&i.Review.HasSpoilers,
		&i.Review.HelpfulCount,
		&i.Review.DeletedAt,
		&i.Review.CreatedAt,
		&i.Review.UpdatedAt,
		&i.User.ID,
		&i.User.Email,
		&i.User.Username,
		&i.User.PasswordHash,
		&i.User.DiscordID,
		&i.User.AvatarUrl,
		&i.User.Bio,
		&i.User.FavoriteGenres,
		&i.User.Role,
		&i.User.EmailVerifiedAt,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.Anime.ID,
		&i.Anime.AnilistID,
		&i.Anime.TitleRomaji,
		&i.Anime.TitleEnglish,
		&i.Anime.TitleNative,
		&i.Anime.Synonyms,
		&i.Anime.Description,
		&i.Anime.Format,
		&i.Anime.Status,
		&i.Anime.Season,
		&i.Anime.SeasonYear,
		&i.Anime.EpisodesCount,
		&i.Anime.DurationMin,
		&i.Anime.Genres,
		&i.Anime.Tags,
		&i.Anime.Studios,
		&i.Anime.CoverImage,
		&i.Anime.CoverColor,
		&i.Anime.BannerImage,
		&i.Anime.AverageScore,
		&i.Anime.Popularity,
		&i.Anime.AnilistTrending,
		&i.Anime.IsAdult,
		&i.Anime.NextAiringAt,
		&i.Anime.NextAiringEpisode,
		&i.Anime.SyncedAt,
		&i.Anime.CreatedAt,
		&i.Anime.UpdatedAt,
		&i.Anime.SearchDoc,
		&i.Anime.MalID,
	)
	return i, err
}

const getReviewRow = `-- name: GetReviewRow :one
SELECT id, user_id, anime_id, body, score, has_spoilers, helpful_count, deleted_at, created_at, updated_at FROM reviews WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetReviewRow(ctx context.Context, id int64) (Review, error) {
	row := q.db.QueryRow(ctx, getReviewRow, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AnimeID,
		&i.Body,
		&i.Score,
		&i.HasSpoilers,
		&i.HelpfulCount,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserReviewForAnime = `-- name: GetUserReviewForAnime :one
SELECT id, user_id, anime_id, body, score, has_spoilers, helpful_count, deleted_at, created_at, updated_at FROM reviews
WHERE user_id = $1 AND anime_id = $2 AND deleted_at IS NULL
`

type GetUserReviewForAnimeParams struct {
	UserID  int64
	AnimeID int64
}

func (q *Queries) GetUserReviewForAnime(ctx context.Context, arg GetUserReviewForAnimeParams) (Review, error) {
	row := q.db.QueryRow(ctx, getUserReviewForAnime, arg.UserID, arg.AnimeID)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AnimeID,
		&i.Body,
		&i.Score,
		&i.HasSpoilers,
		&i.HelpfulCount,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReviewsByUser = `-- name: ListReviewsByUser :many
SELECT reviews.id, reviews.user_id, reviews.anime_id, reviews.body, reviews.score, reviews.has_spoilers, reviews.helpful_count, reviews.deleted_at, reviews.created_at, reviews.updated_at, anime.id, anime.anilist_id, anime.title_romaji, anime.title_english, anime.title_native, anime.synonyms, anime.description, anime.format, anime.status, anime.season, anime.season_year, anime.episodes_count, anime.duration_min, anime.genres, anime.tags, anime.studios, anime.cover_image, anime.cover_color, anime.banner_image, anime.average_score, anime.popularity, anime.anilist_trending, anime.is_adult, anime.next_airing_at, anime.next_airing_episode, anime.synced_at, anime.created_at, anime.updated_at, anime.search_doc, anime.mal_id
FROM reviews
JOIN anime ON anime.id = reviews.anime_id
WHERE reviews.user_id = $1 AND reviews.deleted_at IS NULL
ORDER BY reviews.created_at DESC
LIMIT $2 OFFSET $3
`

type ListReviewsByUserParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

type ListReviewsByUserRow struct {
	Review Review
	Anime  Anime
}

func (q *Queries) ListReviewsByUser(ctx context.Context, arg ListReviewsByUserParams) ([]ListReviewsByUserRow, error) {
	rows, err := q.db.Query(ctx, listReviewsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsByUserRow
	for rows.Next() {
		var i ListReviewsByUserRow
		if err := rows.Scan(
			&i.Review.ID,
			&i.Review.UserID,
			&i.Review.AnimeID,
			&i.Review.Body,
			&i.Review.Score,
			&i.Review.HasSpoilers,
			&i.Review.HelpfulCount,
			&i.Review.DeletedAt,
			&i.Review.CreatedAt,
			&i.Review.UpdatedAt,
			&i.Anime.ID,
			&i.Anime.AnilistID,
			&i.Anime.TitleRomaji,
			&i.Anime.TitleEnglish,
			&i.Anime.TitleNative,
			&i.Anime.Synonyms,
			&i.Anime.Description,
			&i.Anime.Format,
			&i.Anime.Status,
			&i.Anime.Season,
			&i.Anime.SeasonYear,
			&i.Anime.EpisodesCount,
			&i.Anime.DurationMin,
			&i.Anime.Genres,
			&i.Anime.Tags,
			&i.Anime.Studios,
			&i.Anime.CoverImage,
			&i.Anime.CoverColor,
			&i.Anime.BannerImage,
			&i.Anime.AverageScore,
			&i.Anime.Popularity,
			&i.Anime.AnilistTrending,
			&i.Anime.IsAdult,
			&i.Anime.NextAiringAt,
			&i.Anime.NextAiringEpisode,
			&i.Anime.SyncedAt,
			&i.Anime.CreatedAt,
			&i.Anime.UpdatedAt,
			&i.Anime.SearchDoc,
			&i.Anime.MalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsForAnime = `-- name: ListReviewsForAnime :many
SELECT reviews.id, reviews.user_id, reviews.anime_id, reviews.body, reviews.score, reviews.has_spoilers, reviews.helpful_count, reviews.deleted_at, reviews.created_at, reviews.updated_at, users.id, users.email, users.username, users.password_hash, users.discord_id, users.avatar_url, users.bio, users.favorite_genres, users.role, users.email_verified_at, users.created_at, users.updated_at
FROM reviews
JOIN users ON users.id = reviews.user_id
WHERE reviews.anime_id = $1 AND reviews.deleted_at IS NULL
ORDER BY reviews.helpful_count DESC, reviews.created_at DESC
LIMIT $2 OFFSET $3
`

type ListReviewsForAnimeParams struct {
	AnimeID int64
	Limit   int32
	Offset  int32
}

type ListReviewsForAnimeRow struct {
	Review Review
	User   User
}

func (q *Queries) ListReviewsForAnime(ctx context.Context, arg ListReviewsForAnimeParams) ([]ListReviewsForAnimeRow, error) {
	rows, err := q.db.Query(ctx, listReviewsForAnime, arg.AnimeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsForAnimeRow
	for rows.Next() {
		var i ListReviewsForAnimeRow
		if err := rows.Scan(
			&i.Review.ID,
			&i.Review.UserID,
			&i.Review.AnimeID,
			&i.Review.Body,
			&i.Review.Score,
			&i.Review.HasSpoilers,
			&i.Review.HelpfulCount,
			&i.Review.DeletedAt,
			&i.Review.CreatedAt,
			&i.Review.UpdatedAt,
			&i.User.ID,
			&i.User.Email,
			&i.User.Username,
			&i.User.PasswordHash,
			&i.User.DiscordID,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.FavoriteGenres,
			&i.User.Role,
			&i.User.EmailVerifiedAt,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeReviewVote = `-- name: RemoveReviewVote :execrows
DELETE FROM review_votes WHERE review_id = $1 AND user_id = $2
`

type RemoveReviewVoteParams struct {
	ReviewID int64
	UserID   int64
}

func (q *Queries) RemoveReviewVote(ctx context.Context, arg RemoveReviewVoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeReviewVote, arg.ReviewID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteReview = `-- name: SoftDeleteReview :execrows
UPDATE reviews SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteReview(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteReview, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateReview = `-- name: UpdateReview :one
UPDATE reviews SET body = $3, score = $4, has_spoilers = $5
WHERE user_id = $1 AND anime_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, anime_id, body, score, has_spoilers, helpful_count, deleted_at, created_at, updated_at
`

type UpdateReviewParams struct {
	UserID      int64
	AnimeID     int64
	Body        string
	Score       int16
	HasSpoilers bool
}

func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, updateReview,
		arg.UserID,
		arg.AnimeID,
		arg.Body,
		arg.Score,
		arg.HasSpoilers,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AnimeID,
		&i.Body,
		&i.Score,
		&i.HasSpoilers,
		&i.HelpfulCount,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userVotesForReviews = `-- name: UserVotesForReviews :many
SELECT review_id FROM review_votes
WHERE user_id = $1 AND review_id = ANY($2::bigint[])
`

type UserVotesForReviewsParams struct {
	UserID  int64
	Column2 []int64
}

func (q *Queries) UserVotesForReviews(ctx context.Context, arg UserVotesForReviewsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, userVotesForReviews, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var review_id int64
		if err := rows.Scan(&review_id); err != nil {
			return nil, err
		}
		items = append(items, review_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
