// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seed.sql

package sqlcgen

import (
	"context"
)

const countFriendships = `-- name: CountFriendships :one
SELECT COUNT(*)::bigint FROM friendships
`

func (q *Queries) CountFriendships(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFriendships)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)::bigint FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const spreadActivityTimestamps = `-- name: SpreadActivityTimestamps :exec

UPDATE activities SET created_at = now() - (random() * interval '13 days')
`

// Seed-only helpers (cmd/seed): never called by the API or worker.
// Demo data lands all at once; smear it across the trending window so decay
// has something to bite on.
func (q *Queries) SpreadActivityTimestamps(ctx context.Context) error {
	_, err := q.db.Exec(ctx, spreadActivityTimestamps)
	return err
}

const spreadListEntryTimestamps = `-- name: SpreadListEntryTimestamps :exec
UPDATE list_entries SET updated_at = now() - (random() * interval '13 days')
`

func (q *Queries) SpreadListEntryTimestamps(ctx context.Context) error {
	_, err := q.db.Exec(ctx, spreadListEntryTimestamps)
	return err
}
