// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_state.sql

package sqlcgen

import (
	"context"
)

const getSyncState = `-- name: GetSyncState :one
SELECT value FROM sync_state WHERE key = $1
`

func (q *Queries) GetSyncState(ctx context.Context, key string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSyncState, key)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const setSyncState = `-- name: SetSyncState :exec
INSERT INTO sync_state (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now()
`

type SetSyncStateParams struct {
	Key   string
	Value []byte
}

func (q *Queries) SetSyncState(ctx context.Context, arg SetSyncStateParams) error {
	_, err := q.db.Exec(ctx, setSyncState, arg.Key, arg.Value)
	return err
}
