// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"
)

const createDiscordUser = `-- name: CreateDiscordUser :one
INSERT INTO users (email, username, discord_id, avatar_url, email_verified_at)
VALUES ($1, $2, $3, $4, now())
RETURNING id, email, username, password_hash, discord_id, avatar_url, bio, favorite_genres, role, email_verified_at, created_at, updated_at, banner_anime_id
`

type CreateDiscordUserParams struct {
	Email     string
	Username  string
	DiscordID *string
	AvatarUrl *string
}

func (q *Queries) CreateDiscordUser(ctx context.Context, arg CreateDiscordUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createDiscordUser,
		arg.Email,
		arg.Username,
		arg.DiscordID,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.DiscordID,
		&i.AvatarUrl,
		&i.Bio,
		&i.FavoriteGenres,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BannerAnimeID,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, username, password_hash)
VALUES ($1, $2, $3)
RETURNING id, email, username, password_hash, discord_id, avatar_url, bio, favorite_genres, role, email_verified_at, created_at, updated_at, banner_anime_id
`

type CreateUserParams struct {
	Email        string
	Username     string
	PasswordHash *string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.DiscordID,
		&i.AvatarUrl,
		&i.Bio,
		&i.FavoriteGenres,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BannerAnimeID,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, username, password_hash, discord_id, avatar_url, bio, favorite_genres, role, email_verified_at, created_at, updated_at, banner_anime_id FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.DiscordID,
		&i.AvatarUrl,
		&i.Bio,
		&i.FavoriteGenres,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BannerAnimeID,
	)
	return i, err
}

const getUserByDiscordID = `-- name: GetUserByDiscordID :one
SELECT id, email, username, password_hash, discord_id, avatar_url, bio, favorite_genres, role, email_verified_at, created_at, updated_at, banner_anime_id FROM users WHERE discord_id = $1
`

func (q *Queries) GetUserByDiscordID(ctx context.Context, discordID *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByDiscordID, discordID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.DiscordID,
		&i.AvatarUrl,
		&i.Bio,
		&i.FavoriteGenres,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BannerAnimeID,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, password_hash, discord_id, avatar_url, bio, favorite_genres, role, email_verified_at, created_at, updated_at, banner_anime_id FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.DiscordID,
		&i.AvatarUrl,
		&i.Bio,
		&i.FavoriteGenres,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BannerAnimeID,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, password_hash, discord_id, avatar_url, bio, favorite_genres, role, email_verified_at, created_at, updated_at, banner_anime_id FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.DiscordID,
		&i.AvatarUrl,
		&i.Bio,
		&i.FavoriteGenres,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BannerAnimeID,
	)
	return i, err
}

const linkDiscord = `-- name: LinkDiscord :exec
UPDATE users SET discord_id = $2, avatar_url = COALESCE(avatar_url, $3) WHERE id = $1
`

type LinkDiscordParams struct {
	ID        int64
	DiscordID *string
	AvatarUrl *string
}

func (q *Queries) LinkDiscord(ctx context.Context, arg LinkDiscordParams) error {
	_, err := q.db.Exec(ctx, linkDiscord, arg.ID, arg.DiscordID, arg.AvatarUrl)
	return err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users SET email_verified_at = now() WHERE id = $1 AND email_verified_at IS NULL
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}

const setPasswordHash = `-- name: SetPasswordHash :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type SetPasswordHashParams struct {
	ID           int64
	PasswordHash *string
}

func (q *Queries) SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) error {
	_, err := q.db.Exec(ctx, setPasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE users SET
  bio = $2,
  avatar_url = $3,
  favorite_genres = $4,
  banner_anime_id = $5
WHERE id = $1
RETURNING id, email, username, password_hash, discord_id, avatar_url, bio, favorite_genres, role, email_verified_at, created_at, updated_at, banner_anime_id
`

type UpdateProfileParams struct {
	ID             int64
	Bio            string
	AvatarUrl      *string
	FavoriteGenres []string
	BannerAnimeID  *int64
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.ID,
		arg.Bio,
		arg.AvatarUrl,
		arg.FavoriteGenres,
		arg.BannerAnimeID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.DiscordID,
		&i.AvatarUrl,
		&i.Bio,
		&i.FavoriteGenres,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BannerAnimeID,
	)
	return i, err
}

const usernameExists = `-- name: UsernameExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE username = $1)
`

func (q *Queries) UsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, usernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
